### ISSUE TITLE
Default fuel tanks not reducing fuel usage past unusable fuel level

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#1408] opened 2022-10-28 17:59 UTC
See: https://forum.flightgear.org/viewtopic.php?f=25&t=40933

I verified this on my installation. On my installation it is only using the default tanks that this is happening. The integral tanks are working as expected.

Another issue we need to fix the "out of fuel" popup is not ever going to be activated as it is based on an empty tank, not a tank  with "unusable" fuel in it.

enigine.nas
~~~
var update = func {
    #this block should be moved out of nasal and into jsbsim or autopilot logic
    var leftTankUsable  = 0;
    var rightTankUsable = 0;
    if (getprop("/consumables/fuel/tank[0]/selected") and getprop("/consumables/fuel/tank[0]/level-gal_us") > 0) leftTankUsable  = 1;
    if (getprop("/consumables/fuel/tank[1]/selected") and getprop("/consumables/fuel/tank[1]/level-gal_us") > 0) rightTankUsable = 1;
    if (getprop("/consumables/fuel/tank[2]/selected") and getprop("/consumables/fuel/tank[2]/level-gal_us") > 0) leftTankUsable  = 1;
    if (getprop("/consumables/fuel/tank[3]/selected") and getprop("/consumables/fuel/tank[3]/level-gal_us") > 0) rightTankUsable = 1;
    var outOfFuel = !(leftTankUsable or rightTankUsable);
~~~

**Comment by dany93** [comment] 2022-11-02 16:35
Hi @wlbragg 

I hope that you're better with this COVID and wish you as quick as possible to recover, with no side effects.

> Changing the c172p-main consumables code to the following fixes the issue. Is this an acceptable fix?.
<unusable-gal_us type="double">1.49</unusable-gal_us>

I'm afraid that this would be a fragile circumventing. It works in this context and this particular value but, as we don't understand why, it is prone to a future bug again.

What I suspect (hypotheses)
- calculation rounding between transmission?
- (rather) delay between calculation and property transmission?

Notice that the tank 4 feeding `propulsion/tank[4]/external-flow-rate-pps` is seen by very short peaks. Which may be missed at transmission.

If I set 
```
<switch name="fuel/from-tank0-to-tank4">
            <default value="0"/>
            <test logic="AND" value="0.02">
```

consumption peaks to feed tank4 last longer when the level is higher than 1.5 gal. At 1.5 gal level the engine does not stop but it coughs.

It seems to not like the small values for` unusable-volume-gal` or `unusable-gal_us`. In fuel.xml, if I replace unusable-gal_us for a numerical value (1, 1.49, 1.5, 6) :
- for 1.49 or 1.5, it does not stop the engine, only the main tank consumption stops at 1.5.
- for 1, it does not stop the engine, only the main tank consumption stops, but worse, at a very approximative value.
- for 1.6 or greater, it works.

The Wiki [JSBSim Fuel System, Capacity and Contents]( https://wiki.flightgear.org/JSBSim_Fuel_System#Capacity_and_Contents:),
says
  > Tank capacity and contents are measured by weight, not by volume.

With

c172p-main.xml, l.675-

```
    <consumables>
        <fuel>
            <tank n="0">
                <name>Left Tank</name>
                <level-gal_us type="double">0</level-gal_us>
                <selected type="bool">false</selected>
                <water-contamination type="double">0.0</water-contamination>
                <sample-water-contamination type="double">0.0</sample-water-contamination>
                <fuel-sample-taken type="bool">false</fuel-sample-taken>
                <!-- <unusable-gal_us type="double">1.5</unusable-gal_us> -->
                <unusable-fuel-lbs type="double">9.03</unusable-fuel-lbs>
            </tank>
```

and

fuel.xml, l.42-56

```
        <switch name="fuel/from-tank0-to-tank4">
            <default value="0"/>
            <test logic="AND" value="0.1">
                propulsion/tank[0]/priority EQ 1 
                propulsion/tank[0]/contents-lbs GT /consumables/fuel/tank[0]/unusable-fuel-lbs
                /consumables/fuel/tank[4]/level-lbs LT 0.05
                propulsion/tank[4]/priority EQ 1
                accelerations/Nz GE 0
                fuel/tank EQ 0
            </test>
        </switch>
```

(the same for tank 1)

It works correctly.

I do not know if it is because we avoid calculations lbs <--> gal or because the set values are higher.

If you choose this solution, taking it for tanks 2 and 3 would be better for consistency. Although it already works (why?) for the  integral tank configuration.

**Comment by dany93** [comment] 2022-11-03 10:45
@wlbragg 
I tried smaller values for `/consumables/fuel/tank[0 and 1]/unusable-fuel-lbs`.
- with unusable-fuel-lbs = 6.02 (1 gal), it works correctly (stops the engine).
- with unusable-fuel-lbs = 0.602 lbs (0.1 gal), it works correctly (stops the engine).

Using fuel-lbs (instead of gal) for calculations is much more robust.

**Comment by dany93** [comment] 2022-11-03 16:16
This issue has been discussed in 2018-2019.
https://github.com/JSBSim-Team/jsbsim/issues/141

This 'unusable fuel' feature was introduced in JSBSim by bcoconni in 2019.
[https://github.com/JSBSim-Team/jsbsim/i ... -450595959](https://github.com/JSBSim-Team/jsbsim/issues/141#issuecomment-450595959)
If the engine were directly fed by a tank, it would easily work (if I understand well). But the c172p engine is fed through a floating chamber. Which means a logic condition with a JSBSim 'switch'.

Whether the issue was completely fixed or not for the c172p is not clear from the discussion. Anyway, the code has been merged.

**Comment by wlbragg** [comment] 2022-11-03 20:55
>Using fuel-lbs (instead of gal) for calculations is much more robust.

So if I understand you, using unusable-fuel-lbs in consumables VS unusable-gal_us seems to fix this issue?

Because, yeah, we're not in control of that conversion from gal to lbs.

I will test and If this is so make the change.

**Comment by wlbragg** [comment] 2022-11-03 20:56
>or because the set values are higher

That could be true as well, but if it works it seems more robust, as you say.

**Comment by wlbragg** [comment] 2022-11-03 21:01
@dany93 

Did you see this merge request?
https://sourceforge.net/p/flightgear/flightgear/merge-requests/303/
If it is rounding, then this is an appropriate fix and we need to do nothing?

**Comment by wlbragg** [comment] 2022-11-04 01:00
>Using fuel-lbs (instead of gal) for calculations is much more robust.
>I will test and If this is so make the change.

It seems to work fine this way, I think this is a reasonable fix. But I would like someone on the JSBSim side to comment on this. I'll post this information to the sourceforge merge request and see if anyone has any comments about it.

**Comment by dany93** [comment] 2022-11-04 13:28
@wlbragg wrote
>Did you see this merge request?
https://sourceforge.net/p/flightgear/flightgear/merge-requests/303/

No, I hadn't seen it.
But now, I understand almost nothing.
- By reading the description, I almost don't understand what the issue is,
- nor what it fixes, and how (for the same reason).
Add to this my absence of knowledge of the C++...

**Comment by dany93** [comment] 2022-11-04 13:55
If you take the -lbs way for every tank, I think that the following converting lines can be deleted.
```
        <fcs_function name="propulsion/tank[0]/contents-volume-gal">
            <function>
                <quotient>
                    <p> propulsion/tank[0]/contents-lbs </p>
                    <p> propulsion/tank[0]/density-lbs_per_gal </p>
                </quotient>
            </function>
        </fcs_function>
```
From my current understanding, the issue was not a JSBSm one, the mistake was the lbs <--> gal conversions. They bring almost nothing, but they add extra code plus this rounding issue.

If the [merge request by property-tree](https://sourceforge.net/u/propertytree/flightgear_fuel_fix/ci/infinite_fuel_fix/) (or "youdontneedtoknow") fixes the issue without changing our c172p code and without other side effects, that's fine. But as I don't understand its code...

**Comment by wlbragg** [comment] 2022-11-04 17:21
>the mistake was the lbs <--> gal conversions. They bring almost nothing, but they add extra code plus this rounding issue.

I agree.

> I don't understand its code...

I think the merge request works because it takes away the rounding calculation. 
remaining >= GetUnusable()
is now
remaining >= 0

Instead of
if 1.5 >= 1.5000000001 =false

it changes to 
if 1.5 >= 0 =true

But it completely removes the need or use of unusable fuel, ie:  GetUnusable().

So I like your fix and I think I will get the merge canceled.

The only remaining question I have is where does this lbs <--> gal conversion happen? Are we doing it in the c172p code, or is that being done under the hood in JSBSim C++ code? Because if it is in the C++ code then it isn't necessarily only our issue, others could for whatever reason do it the way we did. Which, I agree with you, it is unnecessary to make any code convert gal to lbs for no real reason. No matter where it is done.

**Comment by dany93** [comment] 2022-11-04 18:16
Thank you for your explanations

However, when I read
```
  double remaining = Contents - used;
  if (remaining >= 0) { // Reduce contents by amount used.
```
doesn't it come down to considering that `unusable-fuel=0`?
How is unusable-fuel taken into account?

>where does this lbs <--> gal conversion happen? 

It is done:
- by FlightGear (gal_imp, gal-us, gals, m3,...), I think whatever the aircraft is,
- (at least) used by JSBSim  (unusable-volume-gal).

Also used in the "Fuel and Payload" box.
I don't know if using the FG conversion is as risky as using the extra one done in the c172p.

In the c172p code, it is in fuel.xml, for each tank
```
        <fcs_function name="propulsion/tank[0]/contents-volume-gal">
            <function>
                <quotient>
                    <p> propulsion/tank[0]/contents-lbs </p>
                    <p> propulsion/tank[0]/density-lbs_per_gal </p>
                </quotient>
            </function>
        </fcs_function>
```

**Comment by wlbragg** [comment] 2022-11-04 19:14
>it is in fuel.xml, for each tank

Right, thus we should be able to remove it as you stated previously. OK, I am convinced. I'll make the changes and post a merge request here.

**Comment by dany93** [comment] 2022-11-05 16:10
Hi @wlbragg 
I don't know if that's my lack of knowledge but I have the impression that propertytree has merged his commit in FGTank.cpp.
https://sourceforge.net/u/propertytree/flightgear_fuel_fix/ci/infinite_fuel_fix/
https://jsbsim.sourceforge.net/JSBSim/FGTank_8cpp_source.html
(line 263)

I'm concerned because I suspect it can break something. I don't trust.
Please, can you have a look and ask @bcoconni?

_Can everyone merge a commit in JSBSim source without doing a pull request?_

Thank you.

**Comment by bcoconni** [comment] 2022-11-05 17:07
> The only remaining question I have is where does this lbs <--> gal conversion happen? Are we doing it in the c172p code, or is that being done under the hood in JSBSim C++ code? Because if it is in the C++ code then it isn't necessarily only our issue, others could for whatever reason do it the way we did. Which, I agree with you, it is unnecessary to make any code convert gal to lbs for no real reason. No matter where it is done.

The conversion is indeed made in JSBSim C++ code in `FGTank.h`:

```c++
  /** Returns the amount of unusable fuel in the tank.
      @return the amount in lbs. */
  double GetUnusable(void) const {return UnusableVol*Density;}
```

`Density` is the fuel density which defaults to 6.6 and can be specified in the tank XML definition `<density unit="LBS/GAL"> 6.6 </density>`.

**Comment by bcoconni** [comment] 2022-11-05 17:48
To be honest, I'm struggling to understand the problem you are trying to fix. How did you come to the conclusion that the root cause was a rounding error ?
And I am really struggling to see how replacing a comparison by another change anything ?

was:
`propulsion/tank[0]/contents-lbs GT /consumables/fuel/tank[0]/unusable-fuel-lbs`
will be:
`propulsion/tank[0]/contents-volume-gal GT propulsion/tank[0]/unusable-volume-gal`

In both cases, you are comparing a variable to a constant. How do you expect this to prevent the occurrence of the error ? If your `<switch>` condition is sensitive to round-off errors in one case then it seems to me that it will fail as well with the new comparison. It's just that the round-off error that lead to the failure will be modified.

**Comment by wkitty42** [comment] 2022-11-06 10:42
On 11/5/22 1:49 PM, Bertrand Coconnier wrote:
> To be honest, I'm struggling to understand the problem you are trying to fix. 

the problem is that someone on the forums, goes by property_tree i think, 
discovered that in the c172p when the fuel got to the very lowest amount where 
the craft's engine shout sputter and cut off for lack of fuel, it doesn't...

they tested this naturally by letting the craft just run out and by also moving 
the fuel slider(s) in the in-sim dialog box... in each case, the craft's engine 
didn't die from lack of fuel as expected... so they set out to figure what the 
problem is...

> How did you come to the conclusion that the root cause was a rounding error ?

in some of the testing, when the fuel was at its lowest usable amount, the math 
would return that there was (eg) 15.00000001 remaining and the comparison 
formula for being out of fuel was comparing the integer 15 to be greater than or 
equal to 15.00000001... since it was greater than by .00000001, it said the 
engine never ran out of fuel... in the case of property_tree's flight when they 
discovered this, they were able to sputter on in from england into iceland when 
they should have run out of fuel, their engine stopped, and they glided to a 
landing in the ocean...

> And I am really struggling to see how replacing a comparison by another change 
> anything ?
> 
> was:
> |propulsion/tank[0]/contents-lbs GT /consumables/fuel/tank[0]/unusable-fuel-lbs|
> will be:
> |propulsion/tank[0]/contents-volume-gal GT propulsion/tank[0]/unusable-volume-gal|
> 
> In both cases, you are comparing a variable to a constant. How do you expect 
> this to prevent the occurrence of the error ? If your |<switch>| condition is 
> sensitive to round-off errors in one case then it seems to me that it will fail 
> as well with the new comparison. It's just that the round-off error that lead to 
> the failure will be modified.

i'm not sure where this change comes from as i've not reread the whole issue but 
one thing could be if this new comparison's values are trimmed/rounded whereas 
the previously used ones may not be... idk but i'm still having 1st c0ffee since 
wakeup...

**Comment by dany93** [comment] 2022-11-06 14:30
Hi all of you.

Thank you @wkitty42 for your contribution.
@wkitty42 wrote
>---by letting the craft [just run out and] by also moving
the fuel slider(s) in the in-sim dialog box... in each case, the craft's engine
didn't die from lack of fuel as expected...

Not exactly. If we manually drag both sliders below the unusable level, the engine stops.
But **not** if we let it run down to this level. Il this case, only the tank level stops decreasing.
>when the fuel was at its lowest usable amount, the math
would return that there was (eg) 15.00000001 remaining

Illustration:
![contents-volume-gal](https://user-images.githubusercontent.com/11994061/200174921-e6b651d1-c494-4ea2-831a-0e6b5afa8c40.png)

(see at the bottom).

Here's where I am of my investigations...

I'm wondering if there would not be an erratic conflict between 
`/consumables/fuel/tank[0]/unusable-gal_us` (which **exactly 1.5**)
and 
`propulsion/tank[0]/contents-volume-gal GT propulsion/tank[0]/unusable-volume-gal`
where `contents-volume-gal` can be slightly greater (at the last digit) than 1.5.
(possibly slightly lower, but it shouldn't prevent the switch from stopping the flow rate).

This can happen because we have two conversions. A first one, gal --> lbs, which gives FG the expected unities for calculations, then at the end lbs --> gal to give the expected 1.5. Both with a possible error at the last digit.

If I'm right, this could be the explanation of why it works when we use lbs everywhere, avoiding any conversion.

My idea was
The Wiki [JSBSim Fuel System, Capacity and Contents]( https://wiki.flightgear.org/JSBSim_Fuel_System#Capacity_and_Contents:),
says
  > Tank capacity and contents are measured by weight, not by volume.

Hence, better to be as close to the roots. as possible..

**Comment by bcoconni** [comment] 2022-11-06 16:06
Thanks for the explanations @wkitty42 and @dany93. Yet I'm still struggling to make the connection between the round-off error (i.e. 15.0 vs 15.00000001) and the engine continuing to run despite running low on fuel.

> Here's where I am of my investigations...
> 
> I'm wondering if there would not be an erratic conflict between `/consumables/fuel/tank[0]/unusable-gal_us` (which **exactly 1.5**) and `propulsion/tank[0]/contents-volume-gal GT propulsion/tank[0]/unusable-volume-gal` where `contents-volume-gal` can be slightly greater (at the last digit) than 1.5. (possibly slightly lower, but it shouldn't prevent the switch from stopping the flow rate).
> 
> This can happen because we have two conversions. A first one, gal --> lbs, which gives FG the expected unities for calculations, then at the end lbs --> gal to give the expected 1.5. Both with a possible error at the last digit.

Sorry but I have this weird feeling that you are trying to heal the symptoms rather than the disease. I'd assume that the actual bug is that the engine keeps on running while the fuel content of the float chamber is below its unusable amount/volume. Yet you are suggesting a fix which purpose is to make sure that the fuel content can never run below its unusable amount by a tiny value ?

Is your code checking somewhere for an exact match between the fuel content and the unusable content/volume to turn the engine off ?

**Comment by dany93** [comment] 2022-11-06 16:10
It works correctly (the engine stops) if, in fuel.xml, both switches for tank 0 and 1, I set:
```
propulsion/tank[0]/contents-volume-gal GT 1.50000001
propulsion/tank[1]/contents-volume-gal GT 1.500000001
```
As usually, contents-volume-gal = level-gal_us stop decreasing at 1.500000000000001 but, with these settings, it doesn't prevent the switch from working.

It also goes in the direction of a last digit error.

**Comment by bcoconni** [comment] 2022-11-06 16:46
> It works correctly (the engine stops) if, in fuel.xml, both switches for tank 0 and 1, I set:
> 
> ```
> propulsion/tank[0]/contents-volume-gal GT 1.50000001
> propulsion/tank[1]/contents-volume-gal GT 1.500000001
> ```
> 
> As usually, contents-volume-gal = level-gal_us stop decreasing at 1.500000000000001 but, with these settings, it doesn't prevent the switch from working.
> 
> It also goes in the direction of a last digit error.

Well, I suddenly realize that this is a different story than the initial statement https://github.com/c172p-team/c172p/issues/1408#issuecomment-1295366652 from @wlbragg which said that the content could go below the unusable amount and that was what was triggering the bug.

If I now understand correctly, the actual issue is that the content **never reaches** the unusable amount ? Am I correct ?

**Comment by dany93** [comment] 2022-11-06 17:14
>Yet I'm still struggling to make the connection between the round-off error (i.e. 15.0 vs 15.00000001) and the engine continuing to run despite running low on fuel.

In our case it is 1.50000000000000 vs 1.500000000000001. Not important for the reasoning.

> I'd assume that the actual bug is that the engine keeps on running while the fuel content of the float chamber is below its unusable amount/volume

No.
The engine keeps on running while the fuel content of the main tanks [0 and 1] have (almost) reached the unusable amount/volume. "Almost" because they stop decreasing at 1.500000000000001. 
Hence, the switches
`propulsion/tank[0]/contents-volume-gal GT propulsion/tank[0]/unusable-volume-gal`
with unusable-volume-gal = 1.5, are still allowing a flow rate to the float chamber, which never voids.

> you are suggesting a fix which purpose is to make sure that the fuel content can never run below its unusable amount by a tiny value ?

No.
But be reassured. I'm suggesting nothing, asking for nothing. This because I think having found a fix which works (setting unusable-fuel in lbs).
Not sure that it is "the" fix but, up to now, all my observations go in this way.

Our issue comes from:
-  the fact that we feed the engine through an intermediate float chamber. Which is particular. In the usual configuration (engine fed directly from the main tank) I think that your code works "out of the box",
- the fact that the unusable-fuel amount is set in "gal". 

This said, if you find a code fix which also works with a float chamber with not too much effort, that's fine. But I don't ask you to do some long or tricky work for this. Setting the unusable fuel in "lbs" instead of "gal" once in the -set.xml is not a difficult at all.
If the unusable-fuel amount in lbs were the solution (which assumes that my reasoning is correct...), I'd rather suggest that it is the default way. rather than a tricky work.

**Comment by wlbragg** [comment] 2022-11-06 17:19
Hi @bcoconni  yes, my initial description was with a very limited understanding of the exact issue. We were at the very begging of the discussion and that was the best explanation of what appears to be happening.

The following calculation is where propulsion/tank[0]/contents-volume-gal originates

~~~
<fcs_function name="propulsion/tank[0]/contents-volume-gal">
            <function>
                <quotient>
                    <p> propulsion/tank[0]/contents-lbs </p>
                    <p> propulsion/tank[0]/density-lbs_per_gal </p>
                </quotient>
            </function>
        </fcs_function>
~~~

Also note that we have two sets of "different" tank configurations in the c172p, defaut with a capacity of 129.43 and integral with a capacity of 204. It was only the default tanks that produce the bug, the integral tanks never triggered the bug.

**Comment by dany93** [comment] 2022-11-06 17:23
There was a mistake by @wlbragg in his initial messege. (COVID ?...)
>If I now understand correctly, the actual issue is that the content never reaches the unusable amount ? Am I correct ?

Yes.
The main tank (1] and [2] contents never reaches the unusable amount (1.5 gal). They stop at 1.500000000000001.
Because of this (my previous message), 
@dany93 wrote
>Hence, the switches
`propulsion/tank[0]/contents-volume-gal GT propulsion/tank[0]/unusable-volume-gal`
with unusable-volume-gal = 1.5, are still allowing a flow rate to the float chamber, which never voids.

**Comment by wlbragg** [comment] 2022-11-06 17:39
>There was a mistake by @wlbragg in his initial message. (COVID ?...)

Yeah, let blame Covid :) All better, by the way.

**Comment by bcoconni** [comment] 2022-11-06 17:45
Sorry for all the confusion but as I said several times I did not understand what the problem exactly was. So I was asking silly questions and making statements just as silly trying to make the pieces fit. No hard feelings, I hope.

> Please, can you have a look and ask @bcoconni?
> [...]
> But be reassured. I'm suggesting nothing, asking for nothing.

??????

> This because I think having found a fix which works.

That's fine by me. Now that I understand what the problem is, I am convinced that JSBSim needs an update to avoid the fuel contents being stuck to a value slightly above the unusable content.

**Comment by wlbragg** [comment] 2022-11-06 17:52
Yes, I too am concerned that other developers could potentially run into this if they use a conversion. This fix only eliminates the conversion and not the underlying buggy outcome of the conversion.

**Comment by dany93** [comment] 2022-11-06 18:02
@bcoconni 
Many thanks for you contribution.

In this message https://github.com/c172p-team/c172p/issues/1408#issuecomment-1304575167
@dany93 wrote
>Please, can you have a look and ask @bcoconni?

I was concerned because I had the impression that property-tree (or youdontneedtoknow) had merged his commit in FGTank.cpp.
Can you check this, please?

**Comment by bcoconni** [comment] 2022-11-06 18:26
> I was concerned because I had the impression that property-tree (or youdontneedtoknow) had merged his commit in FGTank.cpp.
Can you check this, please?

Sure, but I thought that this topic was already addressed as @wlbragg [requested on SourceForge that the merge request be cancelled or denied](https://sourceforge.net/p/flightgear/flightgear/merge-requests/303/#6ac4).

Generally speaking it is not a good idea to fix JSBSim directly in FlightGear as I am not monitoring every single commit applied to FlightGear. If something wrong is found (or even suspected) about JSBSim, I'd prefer either:
* Opening an issue in the JSBSim project page on GitHub or,
* Opening a ticket in the FlightGear project page on SourceForge (and invite me to that ticket) or,
* Being invited in a discussion just as you did, but only on GitHub, SourceForge or the FlightGear mailing list. I am not participating to discussions on the FlightGear forum because I don't want to be caught in the JSBSim vs YASim flamewar or that kind of silly talk.

As I mentioned above, JSBSim certainly needs a fix so that this conversion issue cannot happen. I'll open an issue in the JSBSim project page and let you know the progress.

**Comment by bcoconni** [comment] 2022-11-06 18:28
Also the fix in JSBSim will most likely not look like the change that *property-tree* (a.k.a *youdontneedtoknow*) submitted.

**Comment by wlbragg** [comment] 2022-11-07 16:42
@bcoconni thanks again for you attention to this.
@dany93 yes, James rejected that merge request.

**Comment by dany93** [comment] 2022-11-08 08:38
Thank you @wlbragg for this information.
I hope that JSBSim has not been polluted.
Please do not go too fast to do and merge changes, see my message https://github.com/JSBSim-Team/jsbsim/issues/759#issuecomment-1306826666.

**Comment by dany93** [comment] 2022-11-08 15:15
@wlbragg @bcoconni 
An  excerpt of the code where I am now.

With a float chamber, I think the best (only?) way is to use a code independently from the JSBSim one.
Without the
 (FG) `/consumables/fuel/tank[0]/unusable-gal_us`
 and
 (JSBSim) ` /fdm/jsbsim/propulsion/tank[0]/unusable-volume-gal` 
hard-coded property names. 
This way, there is no conflict / competition between the JSBSim feature (made for the usual configuration) and the float-chamber feature (which defines its own limits).

**c172p-main.xml**
```
    <consumables>
        <fuel>
            <tank n="0">
                <name>Left Tank</name>
                <level-gal_us type="double">0</level-gal_us>
                <selected type="bool">false</selected>
                <water-contamination type="double">0.0</water-contamination>
                <sample-water-contamination type="double">0.0</sample-water-contamination>
                <fuel-sample-taken type="bool">false</fuel-sample-taken>
                <unusable-vol-gal type="double">1.5</unusable-vol-gal>
            </tank>
```
See `<unusable-vol-gal type="double">1.5</unusable-vol-gal>`
The names and values for unusable contents are at choice (later for lbs, gal,...) and can be set in the -set or -main .xml. At this step, these are only numbers, without units.
Units are defined below, in the fuel.xml file.

**fuel.xml**
```
    <channel name="To Tank6">
        <!-- from Tank 0 (to Collector Tank 4) -->
        <!--<fcs_function name="propulsion/tank[0]/contents-volume-gal">
            <function>
                <quotient>
                    <p> propulsion/tank[0]/contents-lbs </p>
                    <p> propulsion/tank[0]/density-lbs_per_gal </p>
                </quotient>
            </function>
        </fcs_function> -->
        <switch name="fuel/from-tank0-to-tank4">
            <default value="0"/>
            <test logic="AND" value="0.1">
                propulsion/tank[0]/priority EQ 1 
                /consumables/fuel/tank[0]/level-gal_us GT /consumables/fuel/tank[0]/unusable-vol-gal
                /consumables/fuel/tank[4]/level-lbs LT 0.05
                propulsion/tank[4]/priority EQ 1
                accelerations/Nz GE 0
                fuel/tank EQ 0
            </test>
        </switch>
```
See: 
- No need of extra conversion tables (will be deleted),
- `/consumables/fuel/tank[0]/level-gal_us GT /consumables/fuel/tank[0]/unusable-vol-gal`

(same for tank[1], later [2] and [3])

I tested it with default tank(s), it worked for unusable = 1.5 (gal), also for 0.1, 0.5, 7.

If no one  objects, I will do a merge request from this model. Now, I think that's easier for me than for @wlbragg.

**Comment by wlbragg** [comment] 2022-11-08 18:24
@dany93 
I agree! Thank you for continuing to dig.

**Closed** 2022-11-09 21:50 UTC
Labels: bug
