### ISSUE TITLE
Gather a list of features and bugs we fixed in 2019.1

### ISSUE THREAD

**Issue by onox** [c172p-team/c172p#1196] opened 2018-09-02 16:07 UTC
We should gather a list of all the new features, major changes, and bugs we fixed. Please create a list (use \* to create bullet points) here.

**Features:**

* Persistent adjustable pilot seat/view position
* New seat frame modeling
* New fog and frost overlay showing heat and air vent effect
* Wheels sink based on ground cover density
* Tire size influences  tire friction
* Wheels sink based on snow depth
* Snow depth influences tire friction
* Prop spray effect at high rpm in float variant
* New locked brake smoke effect
* Add rudder trim system to interior cabin panel
* Add brake influence to nose wheel steering and disable NWS when airborne
* Animate front caster wheels
* Extend support for CH Throttle Quadrant joystick
* Implement default renderer interior lighting
* Reshape and widen 26" and 36" bush tires to 12" and 15"
* Autostart function includes auto-mixture

**Fixes:**

* Exterior fuselage mesh cleanup
* Fix broken hydrodynamics
* Fix nasal errors and segfaults
* Skis now slide on ice and snow
* Added fallback model support
* Account for the volume of unusable fuel
* Fix cowl plugs issue in tutorials
* Fix invalid version issue
* Adjust damage effect spark size
* Adjust P-factor
* Correct rain animation over windshield
* Correct wheel spin rolling animation ratio
* Set mixture rich to 3000 ft
* Fix visor rotation issue
* Fix ADF to read khz and not mhz
* Fix default values of selected and standby radio frequencies
* Mixture set to 1 at sea level in autostart 
* Fix flap click sound
* Fix animations of COMs, NAVs and ADF knobs
* Correct texture mapping of axles
* Correct texture mapping of interior hydro rudder mechanism

Do not forget to update `NEWS.md` before creating the release. See https://github.com/c172p-team/c172p-detailed/wiki/Release-process-and-versioning

**Comment by legoboyvdlp** [comment] 2019-05-09 20:17
I think we should close this issue and make a new one for 2019.1 unless @onox can edit the title?

**Comment by gilbertohasnofb** [comment] 2019-05-09 20:21
@legoboyvdlp No need for @onox, super @gilbertohasnofb can change titles at will too! :rofl:

**Comment by wlbragg** [comment] 2019-05-10 04:09
@gilbertohasnofb I think I have everything. Feel free to edit!

**Comment by gilbertohasnofb** [comment] 2019-05-10 11:30
@wlbragg Looks good. @legoboyvdlp @dany93 can you confirm you all new features included here? If so, I will make the new release later tonight.

**Comment by dany93** [comment] 2019-05-10 12:54
Confirmed, all new features(just a few for me).

Thank you, @onox and @gilbertohasnofb,
And thank you, @wlbragg for the huge and difficult work you did.

**Comment by gilbertohasnofb** [comment] 2019-05-10 15:34
All right, I will start preparing the release now.

**Closed** 2019-05-10 15:54 UTC
Labels: help wanted

**Comment by gilbertohasnofb** [comment] 2019-05-10 16:02
@wlbragg @dany93 @legoboyvdlp @onox Done! We have a new release :smile: Congratulations to you all for the hard work, this aircraft gets more and more impressive as time goes by. We have no standing PRs and we seem to have fixed all major bugs, as well as added a bunch of new exciting features. 

@onox It was really fun preparing the release, and I hope I did this right. You might want to double check it since this is the first time I did this, but I am 99.999...% sure it all worked as it should.

@everyone Once again, my apologies for been a bit absent recently. In the near future I might not be able to contribute as much as I did in the past, but I will definitely be around and willing to do at least some work from time to time. @wlbragg ping me when you decide what to tackle next, perhaps the glass effect could be a good place to start? I would love to have a scratched windshield that gets annoying when the sun is in the pulot's face :smile: 

Thanks to you all once again. :tada:

**Comment by wlbragg** [comment] 2019-05-10 20:23
@gilbertohasnofb thank you for cutting the release, I was dreading that part, but you seemed to have no issues with it, I'm thankful for that and it was a hug relief for me to have that done. Thank you! I'll ping them on the dev list and see if they will take it from here.

@everyone
Ditto from me, thank you to all that help get this to this stage. I've got so many projects I am wanting to put time in, it's getting overwhelming. Time to work smarter and not harder!
Thanks everyone!

**Comment by gilbertohasnofb** [comment] 2019-05-10 22:42
> I was dreading that part, but you seemed to have no issues with it

Well, thanks to @onox 's wonderfully detailed instructions, making a release is actually quite easy. One just needs to make sure that all `2019.1` and `2019.2-git` tags and commit comments are correct, there were many that needed to be changed.

**Comment by gilbertohasnofb** [comment] 2019-05-10 22:43
And I am happy to make the next releases as well, even if I am busy. It took me just a handful of minutes.

**Comment by onox** [comment] 2019-05-11 20:59
> @onox It was really fun preparing the release, and I hope I did this right. You might want to double check it since this is the first time I did this, but I am 99.999...% sure it all worked as it should.

@gilbertohasnofb Thanks for doing this release! :smile: Everything looks alright from the Github web interface. I only deleted the extraneous `*` in front of `Fixes:` in the release notes (but this was a typo in the instructions on the wiki - fixed it there as well).

**Comment by onox** [comment] 2019-05-11 21:06
@gilbertohasnofb One more thing: I've moved any open issues with a 2019.1 features/release milestone to the future features/release milestone, and closed the 2019.1 milestones.

**Comment by gilbertohasnofb** [comment] 2019-05-11 22:19
@onox Yeah, I forgot about moving the opened issues to a new milestone. I will remember to do that next time. Thanks for taking a look at this!
