### ISSUE TITLE
Improvements to the tutorials and checklists

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#906] opened 2017-02-15 19:27 UTC
Work on several improvements to the tutorials and checklists:

- all the securing elements can be forced even if "securing aircraft" is false, which is a bit messy (e.g. if your "securing aircraft" is false, you can still add a pitot tube cover via the checklist but then can't remove it by clicking on it. similar stuff for tie-downs, chocks, etc). So better is to deactivated the [>] buttons if that property is false. For instance, this can be accomplished by using a `<condition>` block for that, e.g.:

```
            <binding>
                <command>property-assign</command>
                <property>sim/model/c172p/securing/pitot-cover-visible</property>
                <value type="bool">true</value>
            </binding>
```

becomes:

```
            <binding>
                <condition>
                    <property>/sim/model/c172p/securing/allow-securing-aircraft</property>
                </condition>
                <command>property-assign</command>
                <property>sim/model/c172p/securing/pitot-cover-visible</property>
                <value type="bool">true</value>
            </binding>
```

(It's a pity that `<enable>` does not seem to work with a checklist item, as it not only disables a button but as well make it look disabled.)

- Also, in the tutorial "Checklist: Securing Airplane", you can for some reason add a pitot tube cover even if the securing aircraft is `false`, which is not possible outside the tutorial. This seems potentially buggy so forcing that option to `true` is really important in all these

- I tried loading the tutorial "Securing Aircraft" and it didn't take me to Barcelona, is that intended? I think all tutorials should take place in Barcelona, except for the "Checklist: <something>" types.

- We now have static objects, including ladders, which can be activated in the Ground Equipment dialog. This ladder can be climber by the walker, making it easier to click on the fuel tank caps to add/remove fuel. This could be added to the pre-flight check tutorial.

**Comment by gilbertohasnofb** [comment] 2017-02-15 19:28
@dg-505 we also have this opened https://github.com/c172p-team/c172p-detailed/issues/587 and the only item left is to incorporate the static objects, then we can close that issue

**Comment by wkitty42** [comment] 2018-03-26 19:01
this is the first issue i find when looking back for tutorial related stuff... is it possible to have the tutorials check for starting with the craft in a crashed condition and display a message that they may need to download the scenery for that area before trying to run that tutorial again? this from a recent topic on the forum where someone was trying the tutorials at LEBL but was transferred to LELL for one of the tutorials... i think their FG is 2017.3... if i can find my way back here, i'll try to remember to add a link to the topic on the forum...

**Comment by gilbertohasnofb** [comment] 2018-03-26 21:24
The issue is the rotation of default airport at every 3 months, it takes a lot of manpower to change all tutorials and people just lost interest in keeping up with that. The error message sounds fine, but to be honest that could just be implemented by the devs themselves for ANY crashed aircraft on ANY scenery. My 2 cents.

**Comment by wkitty42** [comment] 2018-03-27 01:08
On 03/26/2018 05:24 PM, Gilberto Agostinho wrote:
> The issue is the rotation of default airport at every 3 months, it takes a lot 
> of manpower to change all tutorials and people just lost interest in keeping up 
> with that.


exactly and that's what i tried to explain to them...


> The error message sounds fine, but to be honest that could just be 
> implemented by the devs themselves for ANY crashed aircraft on ANY scenery.


interesting... i don't know how that could be done without invoking some sort of 
preconditions about a tutorial but hey, i'm behind it if someone wants to 
present it on the dev list :)


> My 2 cents.


i'll put it in the jar along with my donation :) :) :)

**Comment by gilbertohasnofb** [comment] 2018-03-27 09:28
I am just saying that I don't think we should implement this on the aircraft side. Why should every aircraft developer bother in checking if the scenery exists or not? Why doesn't the sim alert them? That should be trivial from the side of the FG devs.

**Comment by wkitty42** [comment] 2018-03-27 16:29
On 03/27/2018 05:28 AM, Gilberto Agostinho wrote:
> I am just saying that I don't think we should implement this on the aircraft 
> side. Why should every aircraft developer bother in checking if the scenery 
> exists or not? Why doesn't the sim alert them? That should be trivial from the 
> side of the FG devs.


i have no problem with that... it is one of those "six for one, half dozen for 
another" things :)

**Comment by gilbertohasnofb** [comment] 2018-07-04 18:59
@legoboyvdlp since you are working on the tutorials could you check the relevance of this issue?

**Comment by legoboyvdlp** [comment] 2018-07-04 20:47
This seems to be the issue I have currently:

> I tried loading the tutorial "Securing Aircraft" and it didn't take me to Barcelona, is that intended? I think all tutorials should take place in Barcelona, except for the "Checklist: " types.


Looks like the issue is longstanding... 
Anyway, sure I can. Might take a while though.

**Comment by gilbertohasnofb** [comment] 2018-08-08 11:37
@legoboyvdlp now that you finished working on the tutorials and your work has been merged, could you please update me on this issue here. Is this still an issue, is there anything left to be implemented?

**Comment by legoboyvdlp** [comment] 2018-08-08 11:53
I didn't implement any of this actually. I can do it - so I take it you just want securing aircraft added to the condition for the checklists, and securing aircraft forced to "true" in the tutorials? The ladder (as far as I know) can't be climbed by the walker any more, at least, it didn't work when I tried it. So I think we can skip that.

**Comment by gilbertohasnofb** [comment] 2018-08-08 11:55
That would be great, lego! I will test the ladder later and let you know.

**Comment by gilbertohasnofb** [comment] 2018-08-08 11:57
Also do check if this is still relevant:

> Also, in the tutorial "Checklist: Securing Airplane", you can for some reason add a pitot tube cover even if the securing aircraft is `false`, which is not possible outside the tutorial. This seems potentially buggy so forcing that option to `true` is really important in all these

**Comment by legoboyvdlp** [comment] 2018-08-08 15:56
> Also, in the tutorial "Checklist: Securing Airplane", you can for some reason add a pitot tube cover even if the securing aircraft is false, which is not possible outside the tutorial. This seems potentially buggy so forcing that option to true is really important in all these

I don't think it is possible to modify those Checklist: X tutorials at all unfortunately - please correct me if I'm wrong.

**Comment by legoboyvdlp** [comment] 2018-08-08 16:03
![image](https://user-images.githubusercontent.com/10434911/43849241-e91b20d8-9b2c-11e8-865c-44c8d9f00f0c.png)

![image](https://user-images.githubusercontent.com/10434911/43849260-f1a1941c-9b2c-11e8-888e-b515cbd054de.png)


I think we've solved that, and I fixed the not-at-Barcelona already (hopefully!). So, now to the Checklist: tutorials...

**Comment by legoboyvdlp** [comment] 2018-08-08 16:10
You now cannot secure the aircraft without the securing aircraft being enabled. However, it will still prompt you to do it - the tutorial will just read out the steps and continue to the end.

**Comment by gilbertohasnofb** [comment] 2018-08-08 18:48
@legoboyvdlp I left a couple of comments in the code, please take a look. Besides those, here are a couple of other things:

* In the `Checklist: Securing Aircraft` tutorial all circles are off. I suspect all other `Checklist: [...]` types of tutorials will be the same since they have not been updated after the cockpit lift. Would you consider fixing this in this same PR?
* I really hate that joke of doors needing to be locked `so that nobody can steal your airplane`. Perhaps we could remove it?
* now for the regular `Securing Aircraft` proper Tutorial, we really should set the aircraft to a proper state before it starts. For instance, I loaded it with the aircraft engine off and that remained off once the tutorial loaded. For me that defeats the purpose and IMO all relevant switches should be on, the parking brake should be off, securing items should not be there, securing should be enabled and the engine should be running at just above 1000 RPM. This way the user has to properly interact.
* in this same tutorial, the purple circle when closing the door circle is not on the strap since we moved it a bit backwards
* the pitot tube camera is wrong, it takes me to 'inside' the wing.
* finally, the tutorial title should be properly capitalized, it should be `Securing Aircraft` and not `Securing aircraft` for the sake of consistency.

**Comment by gilbertohasnofb** [comment] 2018-08-08 18:48
> You now cannot secure the aircraft without the securing aircraft being enabled. However, it will still prompt you to do it - the tutorial will just read out the steps and continue to the end.

See my comments in the code, that logic was not correct.

**Comment by gilbertohasnofb** [comment] 2018-08-08 18:50
> I don't think it is possible to modify those Checklist: X tutorials at all unfortunately - please correct me if I'm wrong.

Those correspond to the checklist themselves so we can't (or shouldn't, don't know if it's possible) force properties such as setting securing items. Just let's leave them like that, but the bug I reported about the pitot tube being still clickeable is still there. But no biggie, I feel this whole Checklist: X tutorials are potentially a bit buggy

**Comment by legoboyvdlp** [comment] 2018-08-08 22:33
> In the Checklist: Securing Aircraft tutorial all circles are off. I suspect all other Checklist: [...] types of tutorials will be the same since they have not been updated after the cockpit lift. Would you consider fixing this in this same PR?


I have no idea where those circles are, they don't seem to be in the checklist file or am I totally blind? 


> in this same tutorial, the purple circle when closing the door circle is not on the strap since we moved it a bit backwards

That needs changed in all the tutorials involving the door as well (for my own reference as I look back to this comment)

> See my comments in the code, that logic was not correct.

I'm fairly sure it was correct, as the items still appeared in the checklist when I didn't have that logic - only they were amber, and it was impossible to set them to green meaning users could potentially get confused as to why they can't get the checklist fully green.




However - I had a thought... What about enabling the securing aircraft in the checklists, i.e. Clicking the > will force it to be true using property-assign, thus avoiding the problem altogether? 

> I feel this whole Checklist: X tutorials are potentially a bit buggy

I agree and wish we could remove them... They should not be present if other tutorials are defined imho...

**Comment by gilbertohasnofb** [comment] 2018-08-09 09:52
> I have no idea where those circles are, they don't seem to be in the checklist file or am I totally blind?

Isn't it defined in those `marker` tags, e.g.:

```
            <marker>
                <x-m>-0.3608</x-m>
                <y-m>0.1725</y-m>
                <z-m>-0.2325</z-m>
                <scale>4.2667</scale>
            </marker>
```

> That needs changed in all the tutorials involving the door as well (for my own reference as I look back to this comment)

Do you think you can take care of that in this PR?

> I'm fairly sure it was correct

Yes, I think you were. 

> However - I had a thought... What about enabling the securing aircraft in the checklists, i.e. Clicking the > will force it to be true using property-assign, thus avoiding the problem altogether?

I am inclined to agree with you on this one. The only thing is that I don't particularly like changing an option 'behind the user's back', if you know what I mean. But then again, if they chose to go to the securing aircraft tutorial then they _must_ want securing items I suppose. But will this affect the regular checklist? That is, will this property get enforced by opening the checklist or something? Do give it a try, I think that if you can pull this off it will be great!

> I agree and wish we could remove them... They should not be present if other tutorials are defined imho...

I don't feel that strongly about them :smile: They are buggy but they are a cool option which some people might really appreciate.

**Comment by gilbertohasnofb** [comment] 2018-08-09 13:43
> I was talking about enforcing it by opening the checklist - the securing aircraft tutorial already forces securing to true. wink

But I was talking not about the regular `Securing Aircraft` tutorial but rather about the `Checklist: Securing Aircraft` tutorial. These names are confusing... for the `Securing Aircraft` I noticed that you are forcing that property and that's good. Since the `Checklist: X` tutorials are automatically created, I thought you were suggesting that going through the first item in the checklist would set that property. We _really_ don't want that the user preference is changed just by using the checklist, maybe they just want a checklist for landing, not for securing the aircraft. So see if the first item of the securing checklist can toggle the securing thing on if it's off. But do keep in mind that if the item is not activated due to already fulfilling its conditional then it won't set this property, so you will need to think well about where to add this property assign command.

**Comment by legoboyvdlp** [comment] 2018-08-09 14:01
If you click the ">" for any securing items in the checklist, if securing is off, it is forced to on.
I fixed most of the other things you mentioned in https://github.com/c172p-team/c172p/issues/906#issuecomment-411512165.

**Comment by gilbertohasnofb** [comment] 2018-08-09 14:03
Thank you, I will test everything in the evening and let you know. I also realized that once we have the cowl plugs modelled and implemented we will need to add them to the tutorials and checklists as well, but that will be easy.

**Comment by gilbertohasnofb** [comment] 2018-08-09 19:42
@legoboyvdlp Ok, so a couple more things:

* in the `Checklist: Securing Aircraft` tutorial the position of the circles is still off by some cm. I suspect all other `Checklist: Foobar` types of tutorials will be the same since they have not been updated after the cockpit lift. 

![fg-0](https://user-images.githubusercontent.com/5700795/43921770-aee63bd0-9c14-11e8-87c8-4859cf67a053.jpg)
![fg-1](https://user-images.githubusercontent.com/5700795/43921771-af17b98a-9c14-11e8-9540-e0d25b74e952.jpg)
![fg-2](https://user-images.githubusercontent.com/5700795/43921772-af3b68bc-9c14-11e8-8dce-2d1219e1eaa8.jpg)
![fg-3](https://user-images.githubusercontent.com/5700795/43921773-af5c994c-9c14-11e8-8551-a8c4b396e790.jpg)


Next comments are all about the `Securing Aircraft` tutorial

* there are two puns involving beer in the tutorial and they are pretty bad. See my comments in the code. Would you mind using something more neutral?

* I think you need to turn the 'allow securing aircraft' option after the tutorial is loaded. I tried loading it with that option off and is continued to be off, and the tutorial got stuck on the control lock item.

* is there a way of improving the animation between adding the chock and adding the right tiedown? right now the camera goes through inside the plane.

* actually, a better order would be to use the same order as the pre flight checks: pitot, left tie-down, tail tie-down, right tie-down and finally chocks.

All else seems fixed. Nearly there!

**Comment by gilbertohasnofb** [comment] 2018-08-09 20:42
I am so sorry for being picky and I know what a pain this is but those markers look terrible when they are out of place :cry:

**Comment by gilbertohasnofb** [comment] 2018-08-09 20:42
at least it's only one coordinate that you need to change, not three...

**Comment by legoboyvdlp** [comment] 2018-08-10 12:08
@wlbragg @gilbertohasnofb what is the offset that was added to the panel when it was raised up, surely I could just add that to the z-coordinates?

For the other tutorials I did this manually using the debug > tutorial marker dialog and it was a pain.

**Comment by gilbertohasnofb** [comment] 2018-08-10 13:39
I don't know that value but @wlbragg might be able to tell you. You could also look at the tutorials and compare them two since the circles are fine in the tutorial.

> surely I could just add that to the z-coordinates?

Absolutely! Just keep in mind that not everything in the cockpit was lifted, e.g. trim wheel, fuel selector, thermometer and vent on the top right, etc. So don't blindly add that to absolutely everything.

**Comment by wlbragg** [comment] 2018-08-10 14:49
>I don't know that value but @wlbragg might be able to tell you.

I don't remember.

**Comment by legoboyvdlp** [comment] 2018-08-10 15:56
It looks like it was roughly 0.0256 - measured using tutorial marker ;)

**Closed** 2018-09-01 18:30 UTC
Labels: bug, checklist, enhancement, good first bug, tutorials
