### ISSUE TITLE
Add Digital Clock

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1124] opened 2018-06-14 19:22 UTC
![image](https://user-images.githubusercontent.com/10434911/41433445-eb537de2-7010-11e8-9bdc-2f3746d3ece7.png)

![image](https://user-images.githubusercontent.com/10434911/41433353-8eef1d18-7010-11e8-862c-71c9119476b4.png)

![image](https://user-images.githubusercontent.com/10434911/41433343-8677e7e6-7010-11e8-9df2-a9f2d0e77bed.png)

The POH of the C172P that I have has a description of a digital clock: how would you feel about replacing our analog clock with this one? It seems to be designed to fit precisely in the same "hole" as the analog clock.

![image](https://user-images.githubusercontent.com/10434911/41433498-0f95b2f6-7011-11e8-87aa-761fb9b71eaf.png)
![image](https://user-images.githubusercontent.com/10434911/41433506-165e0c14-7011-11e8-9084-c8000642b7f3.png)

![image](https://user-images.githubusercontent.com/10434911/41433517-1bd7e44e-7011-11e8-9b57-74da063aa815.png)

![image](https://user-images.githubusercontent.com/10434911/41433549-37f92354-7011-11e8-8dd0-f7523004265b.png)
![image](https://user-images.githubusercontent.com/10434911/41433559-3d5fe224-7011-11e8-8baf-622bbd2602c7.png)

**Comment by wlbragg** [comment] 2018-06-14 20:42
@legoboyvdlp thanks for the detail, we have this in the works somewhere, we're going to use canvas for it. I started on it but got distracted on other stuff. You might search the issues for a duplicate of this?

**Comment by gilbertohasnofb** [comment] 2018-06-14 22:49
> we have this in the works somewhere

Do we? I don't recall that. What we recently spoke about using Canvas for was regarding the thermometer, not digital clock.

**Comment by wlbragg** [comment] 2018-06-15 03:50
Oh, ya, your right. My brain is turning to mush. I confused the two.

>The POH of the C172P that I have has a description of a digital clock: how would you feel about replacing our analog clock with this one? It seems to be designed to fit precisely in the same "hole" as the analog clock.

As far as replacing it, I would be against that idea. But as an option, I would be totally for it!

**Comment by gilbertohasnofb** [comment] 2018-06-15 13:36
@wlbragg I agree. All aircrafts of the model P seem to come with an analog clock on the left side of the AIS just like we have in ours. Some owners seem to add an extra clock in particular as to use a chronometer for navigation. The absolute majority of all photos I have of cockpits of the model P only show the analog clock. OH-CTL is one exception with an old style chronometer:

![image](https://user-images.githubusercontent.com/5700795/41470736-6e557752-70a9-11e8-94f3-675ad0382d7b.png)

So we can leave this issue opened as 'nice to have' but I don't think this is critical.

**Comment by legoboyvdlp** [comment] 2018-06-19 11:31
![image](https://user-images.githubusercontent.com/10434911/41594794-885a34c4-73bc-11e8-92d1-6aee1d1c489a.png)

A first attempt. That's just an import to c172p.blend -> its in a seperate .blend, so it doesn't get overwritten or anything. 

The buttons need scaled in.

**Comment by legoboyvdlp** [comment] 2018-06-19 11:40
put it in the wrong hole!!!
![image](https://user-images.githubusercontent.com/10434911/41595234-f4b0de9c-73bd-11e8-86d4-bac6083feba3.png)

**Comment by legoboyvdlp** [comment] 2018-06-19 11:47
In FlightGear:
![image](https://user-images.githubusercontent.com/10434911/41595472-d0f1ab7a-73be-11e8-8aa6-d048ad3024e3.png)
![image](https://user-images.githubusercontent.com/10434911/41595481-d7311958-73be-11e8-80f9-eb8b02fc6bcb.png)

As I said, I'll need to scale the buttons.

@gilbertohasnofb would you be able to create a texture for this instrument?

**Comment by legoboyvdlp** [comment] 2018-06-19 11:57
This image might help:

https://upload.wikimedia.org/wikipedia/commons/a/ab/Old_C172_cockpit_%28F-GVAY%29_%2814375138039%29.jpg

**Comment by gilbertohasnofb** [comment] 2018-06-19 13:32
@legoboyvdlp I thought we had agreed not to replace the default clock, as the model P comes only with a regular analog clock and many of them do not sport a digital clock and stopwatch.

**Comment by legoboyvdlp** [comment] 2018-06-19 14:21
I understood it was agreed that it would be "nice to have" as an option?

**Comment by gilbertohasnofb** [comment] 2018-06-19 15:13
But I thought it would not be a replacement of the default clock but rather added somewhere else in the panel, just like the OH-CTL did with that analog chronometer. But with that said, now that I think about we hardly have any space left for such things since we have so many bells and whistles already. Maybe the only way forward would be to allow the user to replace the default clock, but I am not sure anyone would do that in RL. What do you suggest? And @wlbragg do you have any ideas?

**Comment by gilbertohasnofb** [comment] 2018-06-19 15:14
@legoboyvdlp have you ever seen any model P with a digital clock? Perhaps try looking at http://www.airliners.net/search?keywords=172p+cockpit&sortBy=dateAccepted&sortOrder=desc&perPage=36&display=detail

**Comment by gilbertohasnofb** [comment] 2018-06-19 15:32
@legoboyvdlp Forget my last comments, I did find a couple of photos of a replaced clock, e.g.:

![](http://imgproc.airliners.net/photos/airliners/2/4/9/2532942.jpg?v=v40)

I will create the texture. We can then add an option to the Aircraft Options dialog:

`[X] Digital clock`

**Comment by legoboyvdlp** [comment] 2018-06-19 16:45
Thanks! :)

Another option is to use the space on the right panel (where some 172s have the EGT and carb temp instruments -> last one would be good to add maybe if we can find some with it - info is in the POH), but that would mean cutting a hole.

**Comment by gilbertohasnofb** [comment] 2018-06-19 18:06
> but that would mean cutting a hole.

that would be a headache, and that corner is busy with the GPS and amphibian gear. Let's just make an option in the menu, is that all right with you? This is also nice since all photos I say had the digital clock replacing the analogue one.

And here are the textures:

![clock-digital](https://user-images.githubusercontent.com/5700795/41615703-dc0fc6e2-73f3-11e8-907c-5d314e33d314.png)

![digits](https://user-images.githubusercontent.com/5700795/41615704-dc30c518-73f3-11e8-8a4c-2b8ae0847017.png)

**Comment by legoboyvdlp** [comment] 2018-06-19 18:42
Awesome job!

**Comment by gilbertohasnofb** [comment] 2018-06-19 18:48
@legoboyvdlp Remember that you will also need a lightmap for this clock

**Comment by legoboyvdlp** [comment] 2018-06-19 19:44
Just a backlight, and the effect of the dome light / flood light - not the post light. So just 3/4 😛

**Comment by legoboyvdlp** [comment] 2018-06-20 09:09
![image](https://user-images.githubusercontent.com/10434911/41647995-a2c3cf88-746f-11e8-8cf0-578e2b354436.png)

![image](https://user-images.githubusercontent.com/10434911/41648814-dfee4dd2-7471-11e8-88d8-2d43f15ed838.png)

@onox I started this off from master and not interior-updates. What do I do to start it off from interior-updates, rebase it? And is it ok to pull-request into interior-updates?

**Comment by legoboyvdlp** [comment] 2018-06-20 09:14
It will be just three files, a texture, a .xml, and a .ac. I'm going to try and use OSGtext to make the display...

**Comment by legoboyvdlp** [comment] 2018-06-20 12:42
Hi there,
@wlbragg I have opened a pull request. What I would need you to do is make the dome light / flood light affect the digital clock. Also, I'm not sure if I added the integral light in correctly, can you check that?

But I'll need @onox 's help to cleanup all the merge commits 😩 

Also, I didn't connect the clock to the electrical system, I will need help as how to do that.

 I hope I got all the tabs out 🙏 (@onox 😜 )

Thanks,
Jonathan

**Comment by gilbertohasnofb** [comment] 2018-06-20 14:44
@legoboyvdlp maybe next time we should all implement one feature at a time if they conflict with others. It's messy to depend on an open PR in order to create a new branch and it would have been easier to just wait a bit longer. Although @onox might know some better ways.

**Closed** 2018-08-22 18:01 UTC
Labels: 3D model, enhancement
