### ISSUE TITLE
Mouse scroll to change zoom doesn't work anymore.

### ISSUE THREAD

**Issue by Megaf** [c172p-team/c172p#1373] opened 2021-07-03 18:59 UTC
As the title says. You can no longer change FOV with the mouse wheel.

**Comment by wlbragg** [comment] 2021-07-03 19:22
What version? It's working on every version I know of including master and the fg1000 branch.

**Comment by Megaf** [comment] 2021-07-03 20:51
Please, in normal mouse mouse, try to change FOV by holding right button and scrolling.

Thanks.

**Comment by wlbragg** [comment] 2021-07-03 22:23
I don't think we have done any code specific to the c172p that would change mouse behavior. I'm afraid this would be a core issue.
The only mouse FOV change I have ever used is middle mouse scroll wheel and it still works as it always has.

**Comment by Megaf** [comment] 2021-07-03 22:58
Thanks,
I does work with the PA-28, F-14, C182 and so on.
I believe it stopped working when the behavior of changing FOV was replaced with changing the camera distance from the aircraft.

**Comment by wlbragg** [comment] 2021-07-03 23:15
Was that something specific we did to the c172p?

**Comment by Megaf** [comment] 2021-07-03 23:47
I noticed a few airplanes switching to this camera moving thing. But that still the minority.

Yet, I have not noticed this bug in any other aircraft. Not that I remember.

Not sure if the move to moving the camera is related to the cause of this bug, it is just a guess.

**Comment by wlbragg** [comment] 2021-07-04 03:03
>I noticed a few airplanes switching to this camera moving thing.

We didn't switch anything related to the view or how it works. I suggest this was a core change in the views that is the issue. Why it affects some aircraft and not others, I have no idea. But I really don't think there is anything we can do locally to fix this or make it the way it used to be as we didn't change anything. I'll leave this open for a bit and see if any one else has anything to add.. You probably want to file a bug report on SourceForge or bring it up on the mailing list.

**Comment by dany93** [comment] 2021-07-04 14:05
@wlbragg wrote
> I don't think we have done any code specific to the c172p that would change mouse behavior

Systems/views.xml contains a logic "View Zoom Enabled".
??

**Comment by wkitty42** [comment] 2021-07-04 15:01
that code has been in place since at least 2018...

**Comment by dany93** [comment] 2021-07-04 15:14
I'm still with FG 2020.3.0, but I remember having noticed a long time ago that the scroll wheel zooming in the cockpit was inactive. I use the keyboard keys x, shift X

**Comment by wkitty42** [comment] 2021-07-04 15:21
a quick look [here](https://github.com/c172p-team/c172p/commits/master/Systems/views.xml) will show all of the changes that Systems/views.xml has gone through... there's only three of them ;)

**Comment by dany93** [comment] 2021-07-04 15:42
I was wandering if we should add (with a "<or>" logic)
                <equals>
                    <property>/sim/current-view/type</property>
                    <value>lookfrom</value>
                </equals>

But trying this code results in the dashboard disappearing at the first action on the scroll wheel.

**Comment by wlbragg** [comment] 2021-07-04 16:42
OK I never use the "default" mouse mode. So as suggested i tried it and verify it doesn't work. But that really didn't mean much to me until I tried it in the J3Cub and it does work. These aircraft are a really close to having the same internal organization and systems. If we can determine why the J3Cub works and the c172p doesn't, maybe we can change it.

**Comment by wkitty42** [comment] 2021-07-04 17:55
maybe @onox can explain what Systems/views.xml is doing and why? perhaps also what needs to be done? i mean, since they are the ones that appear to have done the previous three edits to the file...

**Comment by wlbragg** [comment] 2021-07-04 18:45
@dany93 I just looked at it. You can change it by adding to the "and"
~~~
                <not-equals>
                    <property>/sim/current-view/type</property>
                    <value>lookfrom</value>
                </not-equals>
~~~
What I don't know is what this code was for, what uses lookat and why was the FOV view behavior changed for that view?

**Comment by wlbragg** [comment] 2021-07-04 18:48
For all that matters, why isn't this working as is?  To set 
/sim/current-view/can-change-z-offset = 1 
you need
/sim/current-view/type = "lookat"
and it is not true in the normal interior view?

**Comment by wlbragg** [comment] 2021-07-04 22:05
@Megaf this is corrected and awaiting @legoboyvdlp to test and merge.

**Comment by Megaf** [comment] 2021-07-05 00:06
@wlbragg I greatly appreciate your quick action and investigation.

**Comment by Octal450** [comment] 2021-07-06 06:06
You may wish to check thru my updated version of these view controllers: https://github.com/Octal450/MD-11/blob/master/Nasal/view-controller.nas

This fixes many of the issues mentioned in this thread + many more.

Kind Regards,
Josh

**Comment by wlbragg** [comment] 2021-07-06 16:12
@Octal450 the two issue here are already fixed. One was caused by me when i added the ability to adjust your seat position and make it persistent. The other one is also fixed but is associated with a "view manager" done by others on the project. I don't know why it was required to do anything with the views  such as a "view manager". Maybe if you can explain why you made one, why it was needed, and what exactly it does, I might be in a better position to decide if this is something we could use. Because as it stands now, I am in the dark as to why there is a need for these managers at all? The one issue that was broken that wasn't my fault was caused because we do have a view manager. I have no view manager in the J3Cub and I don't notice any view features that are missing or broken.

**Comment by Octal450** [comment] 2021-07-07 01:13
@wlbragg The goal of the view manager is:
- Manage the FOV zoom, I did this with nasal as with property rule everything breaks when sim is paused and the view can get moved to totally weird positions
- "shortcuts"
- Resetting the view position by the "c" key.

The main reason I suggested looking at my nasal file was to avoid the property rule issues.

Kind Regards,
Josh

**Comment by wlbragg** [comment] 2021-07-07 02:40
Ah, ok, thanks!

**Comment by Megaf** [comment] 2021-07-07 14:18
Not fixed. Please reopen the issue.

**Comment by wkitty42** [comment] 2021-07-07 14:33
it was closed automatically when the merge was made...

**Comment by Megaf** [comment] 2021-07-07 14:36
Demonstration of how it should be. In normal mouse mode, I hold down the right button to pan around, and while holding the right button I scroll to change FOV/Distance.
https://user-images.githubusercontent.com/6201512/124778510-ed759200-df38-11eb-8fa1-eeb429f03d59.mp4

**Comment by dany93** [comment] 2021-07-07 14:44
I don't understand: what are the extra features that make this aircraft needing such a view management? Many (most?) of the others don't, they work out of the box.
Sorry for my lack of knowledge, but I'm wondering...

**Comment by Megaf** [comment] 2021-07-07 14:46
I just want the bug to be fixed...

**Comment by wkitty42** [comment] 2021-07-07 17:33
/me looks again at [Systems/view.nas](https://github.com/c172p-team/c172p/commits/master/Systems/views.xml) and notes the comments, the file's changes dates, and the repo commit descriptions...

i mean, maybe rename view.nas or comment it out of the loading and see what happens? it has been in place for almost 6 years or so...

**Comment by wkitty42** [comment] 2021-07-07 17:33
> Demonstration of how it should be. In normal mouse mode, [...]

what is "normal mouse mode"?

**Comment by Megaf** [comment] 2021-07-07 17:37
Not controlling any flight control surface nor the camera, working as a mouse. Before you press tab to switch between modes.

**Comment by wkitty42** [comment] 2021-07-07 17:41
that's what i thought but wasn't sure...

**Comment by wlbragg** [comment] 2021-07-07 18:11
>I don't see the need for a view manager, maybe as an improvement, in a new issue.
On this issue, I just want the bug to be fixed... The mouse scroll used to work some time ago, and now it doesn't.

Slow down y'all. Let me look at it again and see what happened. It was working for me, maybe I inadvertently messed my fix up. As @Octal450 said, there was a valid reason for making a view manager. Just because other aircraft don't have a manager doesn't mean they don't have the issue the manager was created for. Like I said, and the reason I asked initially, was because the J3Cub doesn't implement a view manager. But I have never tested the actions @Octal450 talks about in his reason for creating his view manager. I doubt @onox made it for no reason.

Unless your willing to roll up your sleeves and test a whole bunch of different scenarios related to viewing, with and without a manager, your merely guessing as to the why's and what's. The easiest solution to the issue at hand was to correct the one issue we know about VS having to rediscover the initial need for the manager in the first place. So long as I am doing the work, at least at this point in time, it is still the easiest path forward for me. Like I said, I thought I had it working.

@Megaf are you capable of pulling these PR before we merge them and testing the fixes when we make them? Rather than have to rely on someone else such as @legoboyvdlp who is taking his time to test these things as a favor to me. It's would be helpful to get the person who created the issue report and is intimately familiar with it to test the fix before we get it merged into master. 
Lets not forget, we all want things to work as we expect them to and we are all volunteering every effort we make to this cause. We'll get it sorted it out eventually.

**Comment by Octal450** [comment] 2021-07-07 19:06
> I don't understand: what are the extra features that make this aircraft needing such a view management? Many (most?) of the others don't, they work out of the box.
> Sorry for my lack of knowledge, but I'm wondering...

Its an enhancement, not a requirement. The distance view system is much nicer for exterior aircraft view angles rather than FoV.
As I said, the MAIN function of my view controller is just porting the property rule file to nasal, to fix the bugs that occur when the sim is paused -> where adjusting the view can sometimes destroy the view setup and require manual reset via property tree or sim restart to fix (because property rules stop when sim is paused). Additional shit is view shortcuts (1 captain view, 2 first officer, 3 overheat etc...) and the last one is the view reset key, so if you moved everything around you can quickly return the view to normal with the "c" key.

Mainly I was talking bout the first, the exterior view system. If you want I will go grab exact steps to duplicate that problem and then send you the fix to test yourself.

Kind Regards,
Josh

**Comment by Megaf** [comment] 2021-07-07 19:25
@wlbragg
> Slow down y'all.

Hah, sorry! It was not my intention to look aggressive! I'm super relaxed on this.

> Let me look at it again and see what happened. It was working for me, maybe I inadvertently messed my fix up

Sure! Not a problem :)

> @Megaf are you capable of pulling these PR before we merge them and testing the fixes when we make them?

I am! I was just busy with work. Will happily test new PRs.

**Comment by wlbragg** [comment] 2021-07-07 20:41
@Megaf good, that'll help. I'll ping you when I think I have it fixed.

**Comment by wlbragg** [comment] 2021-07-07 21:22
@Octal450 
>If you want I will go grab exact steps to duplicate that problem and then send you the fix to test yourself.

Josh, when you gat a chance, if you don't mind, I would appreciate if you would do this.

**Comment by onox** [comment] 2021-07-07 23:27
> > What version? It's working on every version I know of including master and the fg1000 branch.
> Please, in normal mouse mouse, try to change FOV by holding right button and scrolling.

@Megaf "Please" is not a valid version. If a developer requests info from the user in order to reproduce and fix an issue, then you, as a user, need to provide that info.

The whole idea of System/views.xml is that in first person mode you zoom in/out by changing the FOV, as if you're using binoculars. While in third person mode you change the actual distance to the object you're looking at. Changing the FOV in third person mode is very weird and not how other games do it.

So when you say "You can no longer change FOV with the mouse wheel." (I'm assuming you're talking about a third person camera view), I can only answer that this is a feature, not a bug.

Of course the right place to implement such functionality is in FG itself, but since then I have to go through 10 layers of bureaucracy and the FG core devs are unwilling to address the hundreds of paper cuts, I implemented the feature in the aircraft itself.

**Comment by wlbragg** [comment] 2021-07-08 03:09
@onox while I have you here, do you remember much about the details of what you did?
The reason I ask is I did make a solution,, but I don't know if it totally reverses what you did or not. I don't think it did.

There are the two mouse modes, default, the mode where right click does nothing, right press moves your view direction and right press middle scroll wheel @Megaf says used to zoom, but no longer does.

The other mouse mode the right click changes the mouse mode from control to view change to pointer. That is the mode i use and it works as it always has.

I think what might be happening is one of the conditions in the logic statement that activates your view manager code is /sim/current-view/type = lookat. When that is true, you override the original mouse bindings to use you manager. I think maybe that used to be good enough and when it wasn't true the default binding took precedence and worked? Or maybe not, and like now, then when it isn't true there are no more binding of button 3 and 4. 

So what I did was to add the default bindings of button 3 and 4 to your view manager if NOT /sim/current-view/type = lookat or in other words /sim/current-view/type = lookfrom, which is the case when in first person.

Does this make sense to you, do you remember it well enough to have an opinion on my change?

It definitely works and fixes the issue and it should not make any change to when your view manager is supposed to work. It just insures the default view system works when yours isn't active.

**Comment by Megaf** [comment] 2021-07-08 03:39
FOV is changed in FG no matter the camera and, that's how FG calls it.

**Comment by Megaf** [comment] 2021-07-08 03:41
Well, I clearly shown the expected behavior in my last two videos.

Will test the last PR in the morning.

On 8 July 2021 04:09:34 GMT+01:00, wlbragg ***@***.***> wrote:
***@***.*** while I have you here, do you remember much about the details of what you did?

**Comment by onox** [comment] 2021-07-08 07:51
@wlbragg Adding

```xml
<not-equals>
    <property>/sim/current-view/type</property>
    <value>lookfrom</value>
</not-equals>
```

shouldn't do anything because of

```xml
<equals>
    <property>/sim/current-view/type</property>
    <value>lookat</value>
</equals>
```

If `type == "lookat"` then it's also true that `type != "lookfrom"`

From what I remember is that changing `z-offset-m` would cause very strange behavior of the camera for certain camera views. At the time I manually tested for which camera views the distance based zoom would work correctly and disabled it for the other views.

**Comment by dany93** [comment] 2021-07-08 10:52
@Octal450
> Mainly I was talking bout the first, the exterior view system. If you want I will go grab exact steps to duplicate that problem and then send you the fix to test yourself.

No, thank you for your response. That's enough for me.

**Comment by legoboyvdlp** [comment] 2021-07-08 13:12
> The distance view system is much nicer for exterior aircraft view angles rather than FoV.

I disagree with this tbh, I don't like the distance view system a lot. But I'll let others decide if they want it ...

**Comment by wlbragg** [comment] 2021-07-08 17:03
@onox 
>If type == "lookat" then it's also true that type != "lookfrom"

I agree, but it appeared to change something. But then it didn't. I know that makes no sense but that is how it went down. I think @legoboyvdlp experienced the same thing.
But anyway, if you read my last post to you closely, "lookfrom" is no longer the fix. The fix is to add the default button bindings back into your code if the conditions that activate your code are not met. I think by not adding the defaults back in when your code executed, maybe for the first time, the defaults failed to work after your code was no longer active. It's hard to explain, especially because I really don't know what exactly is going on. But it's working for me and didn't change the behavior of your code.

**Comment by wlbragg** [comment] 2021-07-08 17:05
@Megaf  the new PR is ready to test, please do so at your convenience.

**Comment by Megaf** [comment] 2021-07-08 17:24
@legoboyvdlp 
> I disagree with this tbh, I don't like the distance view system a lot. But I'll let others decide if they want it ...

I entirely agree with you, I don't know who had the idea of creating this distance view thing replacing FOV.
Changing FOV is useful to better frame the whole picture, the scenery. Also, it works to actually zoom in on smaller text in the cockpit.

The distance should be set by the developer according to the aircraft size. If a distance changing solution is required, then I'd suggest adding another shortcut instead of replacing FOV.

In the case of this c172p, the problem is even worse. Because the distance views thing is replacing FOV even in tower view position, which makes no sense.

**Comment by Megaf** [comment] 2021-07-08 17:28
> @Megaf the new PR is ready to test, please do so at your convenience.

@wlbragg Tested and commented on the PR. I noticed a new issue though, which I commented above and in the PR.

**Closed** 2021-07-10 11:24 UTC
