### ISSUE TITLE
Attitude indicator updates

### ISSUE THREAD

**Issue by wkitty42** [c172p-team/c172p#1139] opened 2018-07-01 17:46 UTC
i'm copying this from email since i can't find the discussion... i think it might have been part of a PR but i don't know and can't find it...

On 07/01/2018 12:32 PM, wkitty42@gmail.com wrote:
> On 07/01/2018 11:20 AM, Joshua Davidson wrote:
>> Yes, that was an example picture. I've never seen an attitude indicator matching the one we
>> have in FG anywhere on the internet (I've searched long and hard).
>
> i don't know where it came from but the attitude indicator we're using looks
> to be a 3D model... at least it has an .ac file... the ""problem"" seems to
> come from the texture file for it...

so, i've done this...

![20180701-c172p-attitude-indicator-reworked-colors-01](https://user-images.githubusercontent.com/4641713/42137105-9c94bf96-7d34-11e8-8614-29efd269569d.jpg)

![20180701-c172p-attitude-indicator-reworked-colors-02](https://user-images.githubusercontent.com/4641713/42137112-bbab2b9a-7d34-11e8-9050-40ebe14d45d5.jpg)

i can make a PR for this texture if folks want me to... or i can get it to @gilbertohasnofb  and let him clean it up a little bit? i used gimp and got pretty lucky doing the circle selection for the blue outer ring so i could flood fill it... there's still some anti-aliasing in it but this looks like a good start for an hour's work...

i have no idea about that "post light" or why it is located where it is... that's something for @wlbragg to look at... but first we should get this texture in place ;)

**Comment by gilbertohasnofb** [comment] 2018-07-01 17:52
@wkitty42 Please do not ignore my messages and stop dragging this.

> Our AI is modelled after one that is used by the model P. See:
> 
> http://imgproc.airliners.net/photos/airliners/0/6/9/0595960.jpg?v=v40
> http://imgproc.airliners.net/photos/airliners/5/9/9/1774995.jpg?v=v40
> http://imgproc.airliners.net/photos/airliners/1/3/7/4811731.jpg?v=v42736419921
> http://imgproc.airliners.net/photos/airliners/0/5/3/2695350.jpg?v=v40
> http://imgproc.airliners.net/photos/airliners/3/3/0/2558033.jpg?v=v40
> 
>>    A quick search of C172P cockpit will show you tons of cockpits, all with similar indicators.
> 
> Don't use Google Images when searching for a specific model, the search result will show you all sorts of cockpits from all sort of models. The most reliable method I found is to use http://airliners.net/ and search for 172p cockpit, and there you will see that our AI is absolutely common.
> 
> Also, if you have some concrete about improving our gauges then please do open a new issue for that as our conversation here is very out of topic.

**Comment by wkitty42** [comment] 2018-07-01 17:55
i haven't been ignoring you... i'm not dragging this, either... i'm trying to contribute and fix a problem that others have raised... i've done no more than you and wlbragg do when you're going back and forth on an issue and working on it...  no sooner do i get it uploaded and noted where needed and suddenly it is invalid??i guess my work is not good enough? :man_shrugging:

**Comment by gilbertohasnofb** [comment] 2018-07-01 18:06
I had replied to that off-topic discussion with the message I quote above. This has nothing to do with the quality of what you are accomplish, the problem is that the premise is wrong: our AI _is the correct model_ as I showed by providing five photos. I am not happy changing the model or colour or design unless there is a proper reason for it, and in this case I don't think there is.

**Comment by wkitty42** [comment] 2018-07-01 18:40
On 07/01/2018 02:06 PM, Gilberto Agostinho wrote:
> I had replied to that off-topic discussion with the message I quote above.
> This has nothing to do with the quality of what you are accomplish, the
> problem is that the premise is wrong:

is it?


> our AI /is the correct model/ as I showed by providing five photos.

interesting how none of them have the "cage knob" on the bottom right like ours 
is... every single one of them has it in the bottom center... but if you keep 
looking, you do find other 172s with the blue/brown indicator... maybe they put 
in a 3rd party one? maybe they replaced their old one with a new one? i dunno 
but you do seem to be absolutely adamant that this one not go away...


> I am not happy changing the model or colour or design unless there is a
> proper reason for it, and in this case I don't think there is.

well, i hadn't even hardly gotten my finger off the button and you 
unceremoniously marked it as "invalid" and closed it even while i was still 
working on it... that was a shock and it was like you were just throwing it away 
without discussion... i was working on the texture instead of reading posts... i 
was doing that so as to provide at least the option by simply switching the 
textures...

with that said, better would be to take my new texture, name it AI2.png and 
offer a toggle setting where someone could use this new blue/brown attitude 
indicator instead of the old blue/black one... that's a huge sight better than 
"invalid" and throwing the time, effort and honest attempt in the trash...

**Comment by it0uchpods** [comment] 2018-07-01 18:52
Hi,
I can confirm by sitting in the real craft that the indicator does not look flat. You can see depth to it, you can see the oval piece is in front of the behind piece. The "old" indicator had this depth to it, and I am hoping you guys can add such depth to the new one. 

In all the photos you linked, @gilbertohasnofb you can clearly see the oval piece with the markings on it in front of the behind piece (and definitely in real life), while our FG one is just a single surface. This is a big part to the whole "flat" appearance.

**Comment by wlbragg** [comment] 2018-07-01 18:56
@it0uchpods please open a new issue for that exact change, I see it as well and I think I can fix it. But I want to do it in the appropriate place. 
If we decide that we are going to consider a choice of background for the user then I suppose we could tackle both issues here.

**Comment by it0uchpods** [comment] 2018-07-01 18:57
Hi, I'm not home, so I didn't realize this issue was not for the whole indicator when you deferred me here. I'll make a detailed on as soon as I can. Honestly, I think the colors just need to be lightened a bit, then they are fine.

J

**Comment by wkitty42** [comment] 2018-07-01 19:21
On 07/01/2018 02:57 PM, Joshua Davidson wrote:
> Hi, I'm not home, so I didn't realize this issue was not for the whole
> indicator when you deferred me here.


AFAIC this issue can easily be used for the whole indicator... the issue title 
can easily be changed... i created it because i thought you were on about the 
colors and their locations...


that ""oval"" piece you're speaking of is simply a piece of glass or plastic 
with the drawing of the craft representation on it... some have that and others 
just use a dressed up post to hold the craft representation... either way, it 
holds the craft representation off of and in front of the ball or whatever the 
actual moving part of the indicator is... some of them don't even have a ball, 
too... some are flat with a piece that slides up and down representing the 
horizon and pitch angle... then there's another piece, the furthest piece back, 
that rotates to show the roll angle...

so... front to back...

glass cover
craft rep holder (post or glass)
pitch angle slider (moves vertically)
roll angle rotator


> I'll make a detailed on as soon as I can. Honestly, I think the colors just
> need to be lightened a bit, then they are fine.

the colors on the old blue/black one or the ones on the new one i just created? 
you can't lighten black very much :grin:

**Comment by it0uchpods** [comment] 2018-07-01 19:56
> that ""oval"" piece you're speaking of is simply a piece of glass or plastic
with the drawing of the craft representation on it... some have that and others
just use a dressed up post to hold the craft representation

No, that is WRONG. That oval is the pitch scale, and it moves up and down with the pitch. The craft symbol is separate from this.
This image shows perfectly what I mean: http://www.aeronautical.co.za/wp-content/uploads/2017/11/RCA22-15_large.jpg

J

**Comment by gilbertohasnofb** [comment] 2018-07-01 21:36
@wlbragg Here is a good reference for the overall look of the AI from the distance of the pilot's eyesight:

![image](https://user-images.githubusercontent.com/5700795/42138945-8e030dae-7d7d-11e8-9367-770622265493.png)

* the oval shape is visible but barely
* we need to map the background behind the oval piece to a black blue horizon without white lines. I will use the left quadrant of the texture for that (currently we have a white line separating the blue and black parts of the gauge circle in that quadrant and I need to remove it).

**Comment by gilbertohasnofb** [comment] 2018-07-01 21:38
We can also use a not fully transparent texture to simulate the plastic piece upon which the triangle on the top is drawn into. I will work on these textures soon.

**Comment by it0uchpods** [comment] 2018-07-01 21:58
Hi @gilbertohasnofb I agree, ignore that previous model I posted.
The reason the oval is hard to see is because in that picture, it happens to be aligned with the part behind it, creating the appearance of one part :)

That last picture shows that when it goes away from that center position, it is much more visible. I also think adding moving slightly forward and a shadow may help the appearance? As I remember it, it was much more pronounced.

Best Regards,
Josh

**Comment by gilbertohasnofb** [comment] 2018-07-01 22:13
> That last picture shows that when it goes away from that center position, it is much more visible. I also think adding moving slightly forward and a shadow may help the appearance? As I remember it, it was much more pronounced.

@it0uchpods Most models are quite pronounced and the oval part is also curved which gives it a nice impression of depth, but that is not the case of this specific AI as you are noticing. But yes, I think that adding the oval plane a little forward from the back might really do the trick. Cheers!

**Comment by it0uchpods** [comment] 2018-07-01 22:15
I agree, looking forward to see the improvements.

J

**Comment by wkitty42** [comment] 2018-07-01 23:00
On 07/01/2018 05:22 PM, Gilberto Agostinho wrote:
> @wkitty42 <https://github.com/wkitty42> Your issue is called |Attitude Indicator 
> Colors are ""wrong""| and your work involved changing the colours. You opened it 
> /after/ I had posted my message


i never saw your message until later... as previously noted, i saw josh's 
original post, responded and then went to work figuring out where our device was 
located and then working on the colors /because/ that was what i thought he was 
talking about...


> with not one, not two, ... but five reference photos that I know for a fact
> come from a model P. Cessna used several AIs in their 172 lines but the
> sources I am using for the model P have a black and blue AI which we simulate
> quite closely. This is why your issue has been closed as invalid: the colours
> are /not/ ""wrong"".

maybe for the model being used right now but this issue has come up often enough 
over the last year that something must be wrong with it...


>     interesting how none of them have the "cage knob" on the bottom right like
>     ours is...
> 
> Despite your sarcasm this is a valid report which I appreciate.


i wasn't being sarcastic...


>     i dunno but you do seem to be absolutely adamant that this one not go away...
> 
> Maybe that's because I invested a million hours tracking reliable sources and it 
> really irritates me when people post a first result from a Google Search which 
> ends up not even being from the correct model of 172.


others also do a millions hours of research... i can't say who has posted images 
from their first search... without a working crystal ball, i doubt that anyone 
else can say that, either ;)


> Almost every component can end up having two or more versions for a same
> model of 172 and we are not catering for all of them.

i understand that...


> Our philosophy here has always been to pick a reference and follow it.

that must be how we have parts from non-P models as well as from older/newer ones???


>     well, i hadn't even hardly gotten my finger off the button and you
>     unceremoniously marked it as "invalid" and closed it even while i was still
>     working on it...
> 
> Because you ignored (or missed) my message in the other thread


again, you cannot ignore or miss what you don't receive... what do you guys do? 
use only the github web interface and then sit on the refresh buttons???


> about why our AI is the correct model, and because your report is about wrong
> colours which is invalid.

fine... change the issue title like has been done before... i don't mind that... 
what i minded was no discussion at all in this issue before the hammer was 
slammed down... you could easily have posted a message, allowed some discussion 
to take place and then a decision could have been made... this is a team effort, 
isn't it???


>     where someone could use this new blue/brown attitude indicator instead of
>     the old blue/black one...
> 
> That would only work if we assume that the current colours are wrong, but they 
> are not. We used to have a brown and blue AI but we chose to change the model to 
> one that has been reliably showing up in our model P references.


that may explain why i was finding the other attitude indicator texture files 
that i spoke of previously...



> @wlbragg <https://github.com/wlbragg> Here is my proposal:
> 
>   * I will open a new issue for improving the AI
>   * we remove the cage knob and feature as this is a legacy feature from the
>     older AI which does not reflect our model


the cage knob is simply in the wrong place, isn't it? there's only one knob that 
i see in our craft...


>   * I will double check the colours though I think they are fine
>   * we implement the oval shape, but notice that our model is not curved nor
>     thick, it will be really really really subtle (in the photos you can barely
>     tell it)


what about those two little arms that seem to be attached to it? what are they? 
can someone actually hold one of these in their hand a provide a definitive 
description instead of all this guessing from photos?? maybe even take one apart 
and show the parts as they really are? that would solve a lot of this 
speculative stuff...

**Comment by wlbragg** [comment] 2018-07-01 23:18
>we implement the oval shape, but notice that our model is not curved nor thick,

@gilbertohasnofb @legoboyvdlp I am one step ahead of you. I have already done the mesh work to make the Pitch indicator "oval". I actually used the other reference

![ai](https://user-images.githubusercontent.com/11069680/42139683-3c15d000-7d58-11e8-9795-5bcefa08c6a5.png)

which is not an oval but the top and bottom edge is flattened. I also added a depth to that pitch plate so it will have an edge that we can texture white so as to possible set it apart from the Roll plate. It is the roll plate that has the horizontal line I think you want to remove.

>I will double check the colours though I think they are fine

I tried using material setting to make the Roll plate slightly darker than the pitch plate to help it apart, I don't think that is necessarily the correct way to do it (change color) as they probably are the same color. Other than one is farther back and thus may be a bit darker only because of the available light that gets to it.

>it will be really really really subtle (in the photos you can barely tell it)

That is a fact, most of the time you can't even see the distinction between the two.

But @gilbertohasnofb if you do ever so slightly change the color between the "roll" plate and the "pitch" plate, and I make sure the "edge" of the pitch plate is mapped to a white piece of texture, it may be enough to give it the distinction most of the time.

**Comment by it0uchpods** [comment] 2018-07-01 23:38
Neat. Sounds good.

> Other than one is farther back and thus may be a bit darker only because of the available light that gets to it.
Yep, exactly correct. I'm not sure how shadows work with ALS, but maybe there is another way to do it?

J

**Comment by wlbragg** [comment] 2018-07-01 23:46
Here is what it looks like using only a material mapping for color difference. It is too obvious in some light conditions and not obvious at all in others. This is without the p"pitch" edge being mapped to a white texture.

Shows the pitch plate sandwiched between the roll plates.

![ai1](https://user-images.githubusercontent.com/11069680/42140008-eeef6f88-7d5d-11e8-939e-5824c325cbee.jpg)

Same as above with texture.

![ai2](https://user-images.githubusercontent.com/11069680/42140009-ef07d4b0-7d5d-11e8-82ca-40d7da1f0955.jpg)

>We can also use a not fully transparent texture to simulate the plastic piece upon which the triangle on the top is drawn into. I will work on these textures soon.

This is done, you can clearly see it in this image, the Roll Reference Glass. Also this is showing the distinction in certain lighting conditions between the two different material settings of the roll plate and the pitch plate.

![ai3](https://user-images.githubusercontent.com/11069680/42140010-ef1e5668-7d5d-11e8-9c04-d2627604a5a9.jpg)

After the engine was started you can mo longer see any of the pitch plate edges, they all extend past the black circle plate.

![ai4](https://user-images.githubusercontent.com/11069680/42140011-ef312108-7d5d-11e8-9c11-d1e7f18e2aa3.jpg)

This shows the lack of distinction between the roll and pitch plate in other lighting conditions.

![ai5](https://user-images.githubusercontent.com/11069680/42140012-ef4dd866-7d5d-11e8-9d0e-e245eae57ce4.jpg)

Same as above, lack of distinction between the roll and pitch plates.
![ai6](https://user-images.githubusercontent.com/11069680/42140013-ef67945e-7d5d-11e8-94b7-50cd48956074.jpg)

**Comment by it0uchpods** [comment] 2018-07-01 23:48
Looks nice, but I think it is slightly too tall.
Also, can you add the lines above the horizon like: https://i.ebayimg.com/thumbs/images/g/LlgAAOSwKBVZupBi/s-l225.jpg ?

J

**Comment by gilbertohasnofb** [comment] 2018-07-01 23:52
> maybe for the model being used right now but this issue has come up often enough over the last year that something must be wrong with it...

Again, there is no issue. If some people think something is wrong it doesn't make it wrong. I posted five photos of the cockpit, I could have posted five hundred. There is no issue, reality is not up to popular vote. Your argument above is absolutely illogical.

> that must be how we have parts from non-P models as well as from older/newer ones???

What parts are you talking about? If you know of some problems please do let us know. But also do keep in mind that we make mistakes and also that we inherited a messy model. But we do our best to clean both of those up, which is basically what @wlbragg and I have been doing since ages to the best of our abilities and patience.

> use only the github web interface and then sit on the refresh buttons???

Personaly, I don't leave GitHub open all the time, instead when I receive an e-mail I click on 'view it on GitHub' instead of replying to it. This will open the thread, and this way I can check if other people are posting, if photos are being posted as well, if there are reactions of thumbs up/down/smileys to a post, etc. It's really simple.

@wlbragg Looks really good, I will work on the textures tomorrow. But you missed the cage knob which should be removed.

**Comment by wlbragg** [comment] 2018-07-02 00:36
@gilbertohasnofb like I said, I was one step ahead. I had already done all this work prior to any of this discussion. I'll get it removed. I have a local branch called ai-upgrade I will push here shortly.

@wkitty42 I have GitHub pinned to the top of my browser. Anytime a tracked issue is commented on the pinned tap gets a glowing icon of sorts to let you know there is new content, then if you go to the "notifications" screen you have every new notification right there in front of you. I don't even have to open GitHub to know there is a new notification pending. I have to admit that GitHub is doing what they do well, now lets see if MicroFLUFF can screw it up.
https://github.com/notifications

Also, about the background color scheme, we have beat it with a dead horse, more that once. The decision to use the current color scheme has apparently passes the smell test as we have heard relatively nothing from the development community about our choice, barring this issue of course, and it has now been around for multiple releases. So can we please agree to disagree if we must. I know you are more than capable of making and using any texture you so desire and can change it locally if you feel the need to.

I understand how you must have felt to have your issue closed before it even got started, but you need to understand how we feel when you think you have something like that resolved only to have it brought up again, and again.
That is why I said before, technically we should just close the issue with a "won't fix" and an explanation. At that point it would be up to the submitter to reason with us why, as in this case, the issue is different than before or why it should be reexamined. it can always be reopened.

I definitely don't want to see anyone leaving the discussion with hard feeling!

**Comment by wkitty42** [comment] 2018-07-02 14:38
On 07/01/2018 07:52 PM, Gilberto Agostinho wrote:
>> maybe for the model being used right now but this issue has come up often 
>> enough over the last year that something must be wrong with it... >
> Again, there is no issue. If some people think something is wrong it doesn't 
> make it wrong. I posted five photos of the cockpit, I could have posted five 
> hundred. There is no issue, reality is not up to popular vote. Your argument 
> above is absolutely illogical.

your definition of "an issue" is faulty... as i stated, if something is brought 
up numerous times, it IS an issue of some kind, period... that you don't view it 
that way is for you to deal with... that you or someone else may find 5000 
pieces of evidence supporting your side does not negate the fact that there is 
still "an issue" and apparently there's 5000 pieces of evidence supporting the 
other side... we won't even mention that it isn't even about the numbers... 
anyway, i'm not wanting to drag this philosophical muck out any more so EOT 
about this here...


>> that must be how we have parts from non-P models as well as from
>> older/newer ones??? >
> What parts are you talking about?


one of my posts about this, that i wrote but never sent, was based on c172s AI 
parts used in this craft... i think it was the panel but don't remember... 
anyway, i figured out that it wasn't the device in the dashboard so i erased my 
text and started over again...

during the writing of that erased post is when i found all the other AI textures 
where some were blue/black and others were the repeatedly posted blue/brown... 
once i found the right device, i made the texture color changes and posted them 
here because i was excited that i might finally get to do something to really 
contribute more to the project...

what i posted was only a beginning... i had actually planned to copy the AI.ac 
to AI2.ac and fix the internal texture name to AI2.png and then reverse-engineer 
the project to figure out how and where to add an option to switch between the 
two AI models... initial thoughts were to add an "if" statement looking at the 
option property... depending on that option property, either the default 
blue/black AI would be loaded and used or the blue/brown one... since they're 
identical other than the colors, there should be no problem and all the effects 
and everything should just work...


> If you know of some problems please do let us know. But also do keep in mind
> that we make mistakes

of course we do... we all do...


>     use only the github web interface and then sit on the refresh buttons???
> 
> Personaly, I don't leave GitHub open all the time, instead when I receive an 
> e-mail I click on 'view it on GitHub' instead of replying to it.


ahhh... so you have automatic email checking turned on and you're letting the 
click tracking follow you... i prefer not to do either... i manually initiate my 
email checks and i never ever ever ever click on links in emails :shrug:

**Comment by wkitty42** [comment] 2018-07-02 14:46
On 07/01/2018 08:36 PM, wlbragg wrote:
> That is why I said before, technically we should just close the issue with a 
> "won't fix" and an explanation.

that would have been astronomically more acceptable and "Invalid"... "Invalid" 
made me feel like a piece of fecal material being scraped off the bottom of 
someone's shoe... all i ask is that folks watch what they say and do and in 
which order they say and do them... eg: this issue... you can see "Invalid" was 
added first, then the issue was closed, lastly there was a post... the post 
should have been first and the other two items possibly still sitting on the 
sidelines... anyway, as written previously, EOT for me on this subject...


> I definitely don't want to see anyone leaving the discussion with hard
> feeling!

thank you...

**Comment by wlbragg** [comment] 2018-07-02 16:51
I hope no one minds, I renamed and reopened this issue for convenience to work the issues.
@gilbertohasnofb what was the cage knob and cage indicator for. Do you know why it its no longer needed or used?

I've posted a branch with the changes so far. I've done everything I can do to give the parts the appearance of depth.

@gilbertohasnofb don't forget to panel texture needs the AO removed from cage knob area.
Also, if you give the roll texture a slightly darker shade of color than the pitch texture, I will remove the different material settings between the two. Using material settings to do the difference is only appearing under some of the lighting conditions. If you do it in the texture instead then it should be noticeable under all lighting conditions.

**Comment by wlbragg** [comment] 2018-07-02 17:34
Thanks @dany93 we're actually removing it as the model were using doesn't have it. I wonder if this model we are using now is electrical VS vacuum and maybe that is why it doesn't have it anymore.

@gilbertohasnofb that reminds me, I didn't do anything about the cage logic in the XML. I'll do that here shortly.

**Comment by dany93** [comment] 2018-07-02 17:35
Also:
(Caging)

> It means to lock the gymbal bearings in place, ie the gyro can no longer be allowed to keep the standby AH erect, despite still spinning. This prevents damage to the gyro from bumping into it's limits during unusual attitudes etc, and also can be used to erect the gyro quickly during straight and level flight if it's a bit offset due to some hard flying. When caged, the standby AH will show a wings level nose on the horizon attitude.

**Comment by wlbragg** [comment] 2018-07-02 17:37
It appears to never have been programmed to do anything in our system.

**Comment by wkitty42** [comment] 2018-07-02 18:45
On 07/02/2018 01:37 PM, wlbragg wrote:
> It appears to never have been programmed to do anything in our system.


really? if you click the button, there should be a little white arm pop out on 
the top right maybe about the 25 or 30 degree mark... it holds the AI's moving 
parts in place...

**Comment by wlbragg** [comment] 2018-07-02 20:12
> if you click the button, there should be a little white arm pop out on the top right maybe about the 25 or 30 degree mark... it holds the AI's moving parts in place...

Right, but

>and also can be used to erect the gyro quickly during straight and level flight if it's a bit offset due to some hard flying

that is all it does, it doesn't appear to do anything else.

Also anything that it does do apparently is done in the FG source and not in the local aircraft files or system.

So I guess the next question is, does the model we are simulating automatically "limit" the gyro from exceeding limits?

**Comment by gilbertohasnofb** [comment] 2018-07-02 20:53
@wlbragg I will fix the texture and the lightmap now. About the cage button, this model of AI doesn't have one so we need to remove the cageing 3D knob as well as the xml code.

@wkitty42 In hindsight I could have acted differently both in the way of my responses as well as with the `won't fix` tag. My apologies.

**Comment by wlbragg** [comment] 2018-07-02 21:00
>so we need to remove the cageing 3D knob as well as the xml code.

I already removed the cage knob (that has been pushed). I'll remove the code after your done pushing your changes.

**Comment by gilbertohasnofb** [comment] 2018-07-02 21:05
@wlbragg As for the lightmap, it's the panel lightmap that needs to be redone. That map does not have any manual improvement and so it might be worth it to simply re-bake it as it will be tricky to properly remove that knob from all colour channels. Is that too much trouble for you?

**Comment by wkitty42** [comment] 2018-07-03 14:37
On 07/02/2018 04:53 PM, Gilberto Agostinho wrote:
> @wkitty42 In hindsight I could have acted differently both in the way of my
> responses as well as with the |won't fix| tag. My apologies.

thank you, giliberto... i, too, apologize for my having ""popped a breaker"" so 
fast...old ""electronics" ya know? ;) maybe we can work together 
more/better/easier in the future than at odds with...

**Comment by wkitty42** [comment] 2018-07-03 14:40
On 07/03/2018 10:37 AM, wkitty42@gmail.com wrote:
> On 07/02/2018 04:53 PM, Gilberto Agostinho wrote:
>> @wkitty42 In hindsight I could have acted differently both in the way of my
>> responses as well as with the |won't fix| tag. My apologies.
> 
> thank you, giliberto...


my apologies, too, for misspelling your name... mea culpa...

**Comment by gilbertohasnofb** [comment] 2018-07-03 17:00
@wkitty42 I really appreciate that.

> maybe we can work together

Definitely. I can be a bit of a grump sometimes and I recognize it, let's just try to move on. Apologies again.

> misspelling your name

Don't worry at all, I'm living abroad for over a decade and if I had a penny for every time someone misspelt my name I would have a lot of pennies :smile:

**Comment by wlbragg** [comment] 2018-07-03 17:04
>@it0uchpods You are right about the oval piece, but do note that this model we implemented here is quite flatter than the ones you had previously posted so I am still thinking that you have the wrong model in mind. I do agree though that we can improve it a bit by re-adding the oval part back.

We've seen it both ways now, cut off like I have it now, or oval.
Which do we want?

Also my question still stands?
>So I guess the next question is, does the model we are simulating automatically "limit" the gyro from exceeding limits and do we need to account for any of this ourselves?

**Comment by gilbertohasnofb** [comment] 2018-07-03 17:10
> So I guess the next question is, does the model we are simulating automatically "limit" the gyro from exceeding limits and do we need to account for any of this ourselves?

I frankly don't know and this info might be a bit tricky to find out there, but we can try.

**Comment by gilbertohasnofb** [comment] 2018-07-03 17:11
@wlbragg The reference I had posted https://github.com/c172p-team/c172p/issues/1139#issuecomment-401634964 shows a straight cut on top of the oval part so I think that modelling-wise we are fine, your model looks very similar to that reference

**Closed** 2018-07-03 17:16 UTC
Labels: invalid
