### ISSUE TITLE
Taxi light cone misplaced?

### ISSUE THREAD

**Issue by dg-505** [c172p-team/c172p#1357] opened 2021-03-16 11:57 UTC
Hi :wave: 

it seems that in exterior view the taxi light cone comes from the wrong spot and points to the wrong direction:
![fgfs-20210316114524](https://user-images.githubusercontent.com/12293276/111304186-bca1e200-8655-11eb-9191-b532c5bd72aa.png)
In cockpit view however, the taxi light looks correct:
![fgfs-20210316114551](https://user-images.githubusercontent.com/12293276/111304390-f672e880-8655-11eb-9a3b-c781c85bc039.png)
(using latest master branch)

In comparison to that, the *landing light* seems to be correct in both interior and exterior view:
![fgfs-20210316114754](https://user-images.githubusercontent.com/12293276/111304455-0b4f7c00-8656-11eb-853f-276b1cfaa20d.png)
![fgfs-20210316115037](https://user-images.githubusercontent.com/12293276/111304814-77ca7b00-8656-11eb-83e1-1b24faeea835.png)

Thanks for your awesome and outstanding work
Jonathan

**Comment by wlbragg** [comment] 2021-03-16 19:07
Wow, that's interesting. So this is next? I assume this aircraft is then what would be in our master?

**Comment by wlbragg** [comment] 2021-03-16 19:35
I'm not showing this at all? This is what I get i a "normal" exterior view.
Are you suing some kind of altered or alternate view system?
![fgfs-20210316223818](https://user-images.githubusercontent.com/11069680/111369185-ff62ba80-8653-11eb-95fd-addc72ff78dc.png)

This is from #1349.

**Comment by wlbragg** [comment] 2021-03-16 19:43
Checked out the 2020.3 version and I see this?
So I guess I have to ask again, are you using some kind of altered or alternate view system?
It is interesting though that you can see that hard edge out in front appx 50+yards.
![fgfs-20210316224703](https://user-images.githubusercontent.com/11069680/111370103-08a057
00-8655-11eb-95f5-64b2c17ed50b.png)

**Comment by dg-505** [comment] 2021-03-16 20:20
Well, I use the SF FGData git next branch, and the latest daily builds from saiarcot895's PPA on launchpad.
I also double checked that I use the most up-to-date master branch of this aircraft...
Also, I didn't make any modifications in the aircraft files or in FGData.

So this is my command line (set from the launcher):

 --launcher
 --language=en
 --prop:/nasal/local_weather/enabled=true
 --prop:/sim/gui/dialogs/metar/mode/global-weather=false
 --prop:/sim/gui/dialogs/metar/mode/local-weather=true
 --prop:/sim/gui/dialogs/metar/mode/manual-weather=true
 --metar=XXXX 012345Z 15003KT 19SM FEW072 FEW350 25/07 Q1028 NOSIG
 --prop:/environment/weather-scenario=Core high pressure region
 --prop:/local-weather/tmp/tile-management=realistic weather
 --prop:/local-weather/tmp/tile-type=High-pressure-core
 --timeofday=noon
 --prop:/sim/rendering/multi-sample-buffers=1
 --prop:/sim/rendering/multi-samples=4
 --prop:/sim/rendering/texture-cache/cache-enabled=false
 --enable-terrasync
 --enable-sentry
 --developer
 --aircraft-dir=/media/joni/FlightGear/AircraftHangars/git/c172p
 --aircraft=c172p
 --airport=LESB
 --parking-id=1
 --fg-scenery=/media/joni/FlightGear/FlightGearScenery/WS30_UK
 --fg-aircraft=/media/joni/FlightGear/AircraftHangars/git
 --disable-hud-3d
 --httpd=8080
 --fov=85
 --prop:bool:/sim/rendering/shadows/enabled=true
 --prop:int:/sim/rendering/shadows/sun-atlas-size=16384
 --prop:int:/sim/rendering/on-screen-statistics=1
 --prop:double:/sim/time/warp-easing-duration-secs=3

If you need additional information, just tell...

**Comment by wlbragg** [comment] 2021-03-16 22:13
>I also double checked that I use the most up-to-date master branch of this aircraft...

So your not using the FGDATA version of c172p, but your using master out of git hub which would be
https://github.com/c172p-team/c172p?

I can't reproduce this? Can anyone else?

**Comment by dg-505** [comment] 2021-03-16 23:48
I just did a fresh install from `git clone https://github.com/c172p-team/c172p.git`

`git remote -v` yields:
`origin	https://github.com/c172p-team/c172p.git (fetch)`
`origin	https://github.com/c172p-team/c172p.git (push)`

The first entry of `git log` is:
`commit b0e7e5a9d301ecefb5b8552bdf209eb2fec51fa3 (HEAD -> master, origin/master, origin/HEAD)`
`Author: legoboyvdlp R <legoboyvdlp@gmail.com>`
`Date:   Sat Mar 6 12:07:07 2021 +0000`

`    Bump minimum version to 2020.4`

The result is still the same.
It seems that the cone doesn't change it's direction when turning the aircraft:
![fgfs-20210316234104](https://user-images.githubusercontent.com/12293276/111394068-3cfa2e80-86ba-11eb-93f5-858911657221.png)

**Comment by Megaf** [comment] 2021-06-26 13:50
FlightGear 2020.3.9
![fgfs-20210626130626](https://user-images.githubusercontent.com/6201512/123515000-b3c99f00-d68d-11eb-88fb-d2314593f9a6.png)

FlightGear Next (2020.4)
![fgfs-20210626131826](https://user-images.githubusercontent.com/6201512/123515007-baf0ad00-d68d-11eb-92ee-e90a4e7674c3.png)

One big issue is that those lights are still ALS lights and not compositor.

**Comment by wlbragg** [comment] 2021-06-26 15:03
As far as I know, this is not reproducible by any of the developers to date. From the looks of @Megaf last image it appears this issue is not present in his system.
Barring any new information or explanation from @dg-505 I plan to close this issue soon.

>One big issue is that those lights are still ALS lights and not compositor.

As far as that is concerned, the versions available with each release also do not present this issue so I am really suspect that it is a non-issue and may be particular to something specifically askew with @dg-505 setup.

**Closed** 2021-06-27 23:31 UTC
