### ISSUE TITLE
Propeller 3D Model - potentially too thin at the root

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1093] opened 2018-05-09 16:08 UTC
![image](https://user-images.githubusercontent.com/10434911/39825999-29741c58-53ab-11e8-9012-53de8c3ce5a0.png)

Is it just me or the camera angle, or is our propeller a bit too thin in blade width near the spinner?

**Comment by legoboyvdlp** [comment] 2018-05-09 23:17
It looks like our propeller is twisted while the real one is not?

**Comment by gilbertohasnofb** [comment] 2018-05-09 23:33
@legoboyvdlp It's just because of the colour, light and angle in that photo. See these ones, they are clearly twisted:

![](http://www.kyleflemingphotography.com/wp-content/gallery/cessna-172-512/cessna-172-prop.jpg?x83484)

![](https://cdn.weasyl.com/~solariswolfox/submissions/845550/71319710c23a0cf3d29d0eff68eb6af2b1f215a5f133f0226305aa69d7b4eb96/solariswolfox-cessna-172-nose-propellor.jpg)

![](http://asijet.com/Websites/asijet/Ecommerce/Products/55a6aace-b2e9-4ca3-897b-4570288b3a29.JPG)

**Comment by gilbertohasnofb** [comment] 2018-05-09 23:33
This is also very clear in the photo you posted yourself in the issue description.

**Comment by tonghuix** [comment] 2018-05-10 07:49
I think it is because the root of blade twisted too much, nearly parallel to the longitudinal axis of the plane. 

![2018-05-10 15-25-18](https://user-images.githubusercontent.com/423703/39857900-8807f66a-5467-11e8-84f4-ddc80e822e01.png)

For perfect solution, it is better re-model it, but now make it less twist is okay.

I found a video may good help https://www.youtube.com/watch?v=ycE4MEk8Xfs

**Comment by dany93** [comment] 2018-05-10 09:03
@legoboyvdlp wrote:

> It looks like our propeller is twisted while the real one is not?

Every propeller is twisted, to keep a correct AoA from the center to the periphery, to compensate for the difference in linear velocity vs the distance from the axis.

**Comment by tonghuix** [comment] 2018-05-11 03:25
I tried re-modeling it reference the photos that I took at 2018 Zhengzhou Airshow. 

![2018-05-11 11-20-44](https://user-images.githubusercontent.com/423703/39905024-d3853110-550d-11e8-8ac8-43a3edd1ab7d.png)

![c172-prop](https://user-images.githubusercontent.com/423703/39905027-d81a5c0a-550d-11e8-9b99-93b3fdb438b1.jpg)

**Comment by wlbragg** [comment] 2018-05-11 04:01
Below is our existing prop rotated along the Y axis to demonstrate the current thickness. It may be the amount of twist that is the issue or the orientation of the prop twist.
![prop](https://user-images.githubusercontent.com/11069680/39905906-7701c2ea-54a5-11e8-9bbb-49fda3a4043b.jpg)

Also lets not forget there are "many" different typed of props. We really need to be showing images of the same props we use, not just any prop. Plus, we use two different props depending on the engine.

320 engine and prop
~~~
        <engine file="eng_io320">
            <location unit="IN">
                <x> -19.7 </x>
                <y> 0 </y>
                <z> 26.6 </z>
            </location>
            <orient unit="DEG">
                <roll> 0.0 </roll>
                <pitch> 0 </pitch>
                <yaw> 0 </yaw>
            </orient>
            <feed>2</feed> <!-- from intermediate tank (float chamber 2) -->
            <thruster file="prop_75in2f">
            <!-- <thruster file="prop_75in_2f_NACA_15-30deg"> --> <!-- for settling -->
                <location unit="IN">
                    <x> -37.7 </x>
                    <y> 0 </y>
                    <z> 26.6 </z>
                </location>
                <orient unit="DEG">
                    <roll> 0.0 </roll>
                    <pitch> 0.0 </pitch>
                    <yaw> 0.0 </yaw>
                </orient>
                <sense> 1 </sense>
                <p_factor> 5 </p_factor>
            </thruster>
        </engine>
~~~
~~~
<propeller name="Fixed-Pitch 75-inch Two-Blade Propeller">

    <ixx> 1.67 </ixx>
    <diameter unit="IN"> 75.0 </diameter>
    <numblades> 2 </numblades>
    <minpitch> 22 </minpitch>
    <maxpitch> 22 </maxpitch>

    <table name="C_THRUST" type="internal">
        <tableData>
            0.0   0.068
            0.1   0.068
            0.2   0.067
            0.3   0.066
            0.4   0.064
            0.5   0.062
            0.6   0.059
            0.7   0.054
            0.8   0.043
            0.9   0.031
            1.0   0.019
            1.1   0.008
            1.2   -0.001
            1.3   -0.008
            1.4   -0.019
            1.5   -0.029
            1.6   -0.040
            1.7   -0.050
            1.8   -0.057
            1.9   -0.061
            2.0   -0.064
            2.1   -0.066
            2.2   -0.067
            2.3   -0.068
            5.0   -0.068
        </tableData>
    </table>

    <table name="C_POWER" type="internal">
        <tableData>
            0.0   0.0580
            0.1   0.0620
            0.2   0.0600
            0.3   0.0580
            0.4   0.0520
            0.5   0.0457
            0.6   0.0436
            0.7   0.0420
            0.8   0.0372
            0.9   0.0299
            1.0   0.0202
            1.1   -0.0111
            1.2   -0.0075
            1.3   -0.0111
            1.4   -0.0202
            1.5   -0.0280
            1.6   -0.0346
            1.7   -0.0389
            1.8   -0.0421
            1.9   -0.0436
            2.0   -0.0445
            2.1   -0.0445
            2.2   -0.0442
            2.3   -0.0431
            2.4   -0.0424
            5.0   -0.0413
        </tableData>
    </table>

</propeller>
~~~

360 engine and prop
~~~
        <engine file="eng_io360">
            <location unit="IN">
                <x> -19.7 </x>
                <y> 0 </y>
                <z> 26.6 </z>
            </location>
            <orient unit="DEG">
                <roll> 0.0 </roll>
                <pitch> 0 </pitch>
                <yaw> 0 </yaw>
            </orient>
            <feed>3</feed> <!-- from intermediate tank (float chamber 3) -->
            <thruster file="prop_76in2f_NACA_20deg">
            <!-- <thruster file="prop_76in2f_NACA_15-25deg"> --> <!-- for settling -->
                <location unit="IN">
                    <x> -37.7 </x>
                    <y> 0 </y>
                    <z> 26.6 </z>
                </location>
                <orient unit="DEG">
                    <roll> 0.0 </roll>
                    <pitch> 0.0 </pitch>
                    <yaw> 0.0 </yaw>
                </orient>
                <sense> 1 </sense>
                <p_factor> 5 </p_factor>
            </thruster>
        </engine>
~~~
~~~
<!-- 
    Diameter: 76 in (1.93 m)
    Pitch: 62.5 in
    Calculated blade angle: 20° at 75% of the radius
    Data from NACA Report 640 : http://naca.central.cranfield.ac.uk/reports/1938/naca-report-640.pdf
-->

<propeller name="NACA 640 (5868-9) 76-inch 20deg Two-Blade Propeller">

    <ixx> 1.67 </ixx>
    <diameter unit="IN"> 76.0 </diameter>
    <numblades> 2 </numblades>
    <minpitch> 20 </minpitch>
    <maxpitch> 20 </maxpitch>

    <table name="C_THRUST" type="internal">
        <tableData>
            0	   0.1040
            0.1	   0.1040
            0.2	   0.1030
            0.3	   0.1010
            0.4	   0.0930
            0.5	   0.0820
            0.6	   0.0700
            0.7	   0.0550
            0.8	   0.0390
            0.9	   0.0240
            1	   0.0060
            1.1	   -0.0140
            1.2	   -0.0330
            1.3	   -0.0450
            1.5	   -0.0600
            2	   -0.0720
            3	   -0.0800
        </tableData>
    </table>

    <table name="C_POWER" type="internal">
        <tableData>
            0	   0.0660
            0.1	   0.0650
            0.2	   0.0640
            0.3	   0.0625
            0.4	   0.0600
            0.5	   0.0580
            0.6	   0.0540
            0.7	   0.0475
            0.8	   0.0370
            0.9	   0.0260
            1	   0.0100
            1.1	   0.0000
            1.2	   -0.0100
            1.3	   -0.0200
            1.5	   -0.0350
            2	   -0.0500
            3	   -0.0550
        </tableData>
    </table>

</propeller>
~~~

**Comment by gilbertohasnofb** [comment] 2018-05-11 10:54
Guys, please always contact @wlbragg before doing _any_ 3D work, our Blender file is _extremely_ sensitive and it is not git friendly. We cannot have two different PRs both dealing with a same Blender file, else one of them will get ignored.

**Comment by dany93** [comment] 2018-05-11 14:03
Propellers, POH's:
(what I have)

**160 hp** (C172p 1982, POH 12 May 1981)
![160hp-prop-c172p](https://user-images.githubusercontent.com/11994061/39927233-dc74c42e-5531-11e8-826f-291b115d051f.png)

**180 hp** (C72S, POH 552 SP
PROPELLER
Propeller Manufacturer: McOauley Propeller Systems.
Propeller Model Number: 1 A1 70ElJH47660.
Number of Blades: 2.
Propeller Diameter: 76 inches.
Propeller Type: Fixed pitch.

Take this only as a guide for 3D modelling.

In the FDM:
The Thrust and Power curves (the important for the FDM) for the 180 hp is taken from NACA report 640.
These are measured curves for propellers described in the article. Useless for the 3D.
For the 160hp, I don't remember, possibly the initial by Megginson (?).

**Comment by wlbragg** [comment] 2018-05-11 15:55
>We cannot have two different PRs both dealing with a same Blender file, else one of them will get ignored.

For clarity, using your local blend version to demonstrate a proposed change and posting the results is of course OK, it can actually be very helpful to whoever eventually does the Blender work and for discussion. But referring to what @gilbertohasnofb is pointing out, please don't make a blender change that you expect merged into master along with creating a PR for it without consulting first. It will have to be coordinated. Personally I encourage anyone that wants to get their teeth wet in Blender to go for it. We (I) could use the help, it's just as @gilbertohasnofb stated, it is a sensitive file that has many nuances that need to be adhered to and not at all GIT friendly.
I am in a continuous learning cycle every day with the organizational side of the mesh, texture and material settings. The worst thing is discovering a less than optimal setup after the fact and having to backtrack to try to fix it. Something I fear is going to bite me in the butt with the proposed AO and light maps we want to create.

**Comment by legoboyvdlp** [comment] 2018-05-11 16:14
(in terms of lightmaps, if you like, I am familiar with the baking process and would be able to help you in that regard.)

**Comment by tonghuix** [comment] 2018-05-11 23:55
I found some photo of 1C160/DTM7557 propeller from ebay: 

![](https://i.ebayimg.com/images/g/91oAAOSwMlRakG-n/s-l1600.jpg)
![](https://i.ebayimg.com/images/g/RqcAAOSwJ1BakG7l/s-l1600.jpg)
![](https://alphaaviation.aero/wp-content/uploads/048.jpg)
![](https://alphaaviation.aero/wp-content/uploads/056.jpg)

**Comment by gilbertohasnofb** [comment] 2018-05-12 00:11
I am 99% sure that all model P use a propeller with a straight edge as shown in all photos I posted. Also, this website lists a [DTM7557 MCCAULEY PROPELLER](http://www.univair.com/propellers/mccauley/dtm7557-mccauley-propeller/) for sale and it looks like what I came to expect:

![](http://cdn2.bigcommerce.com/server100/dtwuls/products/16935/images/10728/mccauley-propeller-stock-photo__06986.1501793877.1280.1280.jpg?c=2)

I have excellent close up pictures of the OH-CTL and I really suggest we use it as our reference as much as possible as to keep things consistent. Agreed @wlbragg ?

**Comment by tonghuix** [comment] 2018-05-12 01:58
@gilbertohasnofb Please review the left column of the web page, it seems all propeller use this *IDENTICAL* picture, CM7448, DFA9043....etc.

**Comment by tonghuix** [comment] 2018-05-12 04:25
I just re-model the DTM7557 propeller. 

![2018-05-12 10-45-38](https://user-images.githubusercontent.com/423703/39953492-8c14255c-55df-11e8-89fc-0ee009566d0d.png)

Uploaded to my personal repo:  https://github.com/tonghuix/c172p-detailed/blob/master/dev/blender/c172p-prop.blend

**Comment by gilbertohasnofb** [comment] 2018-05-12 12:50
Perhaps the text `STOCK PHOTO - ACTUAL PROPELLER MAY DIFFER FROM IMAGE` written in that image could have alerted me :man_facepalming: 

It seems you are right, @tonghuix, I doubled checked and it turns out most Model P have a round propeller:

![](http://imgproc.airliners.net/photos/airliners/9/3/7/4766739.jpg?v=v4bd9e79c9fa)

Though a few do indeed have a straight one (see half of my photos posted here). In that case, we can go with either of them, perhaps keeping the round as that seems to be more common. Is that fine with you, @wlbragg ?

**Comment by gilbertohasnofb** [comment] 2018-07-29 20:14
@wlbragg would you like to consider improving the propeller for the release? I think the issue is two fold:

* the propeller is way too twisted close to the nose
* the round shape of the propeller is too circular in our model, I think that could be a bit better modelled

**Comment by wlbragg** [comment] 2018-07-30 04:32
@gilbertohasnofb I modified the propeller a bit. This is not the easiest to make changes to because of the texturing involved. So unless it is a glaring problem I don't want to make a lot of changes to it if it is not absolutely necessary. but another round isn't out of the question if needed.

**Comment by gilbertohasnofb** [comment] 2018-07-30 14:35
@wlbragg I think it looks better but the propeller is now having a bit of a strange shape when seen from the front:

![fgfs-screen-001](https://user-images.githubusercontent.com/5700795/43403678-9c8f516a-940d-11e8-848c-77986615d960.jpg)

Notice in the photos how the propeller is thicker at a point B between the extremities A and C:

![image](https://user-images.githubusercontent.com/5700795/43403812-fe91edc8-940d-11e8-8440-5f8673370f49.png)

I know that improving this model is a pain since it is twisted, so what about this?: the c182s has a quite nice propeller model. Could we 'borrow' one of the blades, resize it to match ours and mirror it to make the other side (the 182 is triple bladed). We then just need to UV-map it to our model.

PS: notice the green landing light in that first shot.

**Comment by wlbragg** [comment] 2018-07-30 17:25
>PS: notice the green landing light in that first shot

If I can't reproduce it I don't know where to start to fix it.
I will try to take another look, We may have to ask Thorsten about it.

@gilbertohasnofb I modified a c182s blade. I had to rework the tip and the base a bit, but huge improvement. If you don't mind would you please give credit somewhere in the files, where credit is due, to the original author if you know who created the blades. I would really appreciate it if you would take care of that for me.

**Comment by gilbertohasnofb** [comment] 2018-07-30 17:37
> If I can't reproduce it I don't know where to start to fix it.

Try this. Start using the default launcher, pick SAWB, afternoon and Core high pressure scenario. The light should already be green. It starts to get back to yellow in the evening.

> I modified a c182s blade. I had to rework the tip and the base a bit, but huge improvement. If you don't mind would you please give credit somewhere in the files, where credit is due, to the original author if you know who created the blades. I would really appreciate it if you would take care of that for me.

Wow, that looks really good. Thanks for adapting this! As for who created them, I suppose it was Heiko. @HHS81 can you confirm that?

**Comment by HHS81** [comment] 2018-07-30 18:01
@gilbertohasnofb 
Yep, but even I used a model from Syd Adams for the C182S prop. So it is Syd Adams --> Me --> ....

**Comment by gilbertohasnofb** [comment] 2018-07-30 18:46
@HHS81 Thanks Heiko, I will add a thank note to both of you.

**Comment by gilbertohasnofb** [comment] 2018-07-30 18:56
@wlbragg done, please pull before continuing.

**Closed** 2018-08-07 22:12 UTC
Labels: 3D model, enhancement
