### ISSUE TITLE
Landing Light Color

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1150] opened 2018-07-23 16:25 UTC
![image](https://user-images.githubusercontent.com/10434911/43089756-6476fee2-8e9d-11e8-97fe-53eb99522a53.png)

Some prankster seems to have painted our landing light bulbs? 🤣

**Comment by gilbertohasnofb** [comment] 2018-07-23 16:29
@wlbragg could you take a look at this? :laughing:

**Comment by wlbragg** [comment] 2018-07-23 17:30
Wow, I don't get that so there is nothing for me to look at.

I vaguely remember seeing that once but for the life of me can't remember what the cause of it was or if it was something I fixed. Does the color go away when you don't have the green grass in the background?
Because I am certain the time I saw this that the green grass in the background was the cause. But again I don't remember when or why although I kind of recall it may have been an effect file that was messed up.
What branch are you getting this with and is it up-to-date?

**Comment by legoboyvdlp** [comment] 2018-07-23 17:43
Ah ok - let me check without any grass.
I'm using my tutorials branch.

**Comment by gilbertohasnofb** [comment] 2018-07-23 19:44
I am having some issues here with my FG installation again but I will test this as soon as I can

**Comment by onox** [comment] 2018-07-24 02:13
I have this issue too. Tested at FHAW.

**Comment by wlbragg** [comment] 2018-07-24 02:47
@onox what branch?

**Comment by gilbertohasnofb** [comment] 2018-07-24 19:14
@wlbragg just so that you know, I have been replying to messages but not testing because my FG installation is broken again. Saiarcot's PPA had failed to compile some of the packages and when I went to upload my installation I got some errors and now I can't force the older versions any longer... he said he is working on a fix, so let's hope I am fully back soon.

**Comment by wkitty42** [comment] 2018-07-24 20:36
On 07/24/2018 03:14 PM, Gilberto Agostinho wrote:
> @wlbragg <https://github.com/wlbragg> just so that you know, I have been 
> replying to messages but not testing because my FG installation is broken again. 
> Saiarcot's PPA had failed to compile some of the packages and when I went to 
> upload my installation I got some errors and now I can't force the older 
> versions any longer... he said he is working on a fix, so let's hope I am fully 
> back soon.


i saw something on the forum about a problem with the PPA... i tagged saiarcot 
in and he posted that he was hoping to have it fixed as soon as he was able to 
complete he upload of 2018.2.2... kinda funny but maybe not is that 2018.2.3 was 
branched today... we still have a couple of weeks for 2018.3.1...

**Comment by gilbertohasnofb** [comment] 2018-07-24 20:37
Thanks for the info, I wrote him a private message as well and he is aware of the problem.

**Comment by onox** [comment] 2018-07-25 00:21
@wlbragg the `master` branch.

**Comment by gilbertohasnofb** [comment] 2018-07-25 21:35
@wlbragg I did test this and on my machine the colour and brightness of the landing light changes a little bit according to the time of day as if it's an illuminated object and not a light emitter. Somewhere around dusk time the landing light did get a bit of a green coloration, but nothing like the first screenshot in this thread.

**Comment by wlbragg** [comment] 2018-07-30 22:26
@gilbertohasnofb this worked for me. In the blend the taxi and landing light object used to attach the light to had a green diffuse and specular color assigned to them. It appears that that color becomes prominent under certain lighting conditions (low light).

**Comment by gilbertohasnofb** [comment] 2018-07-31 00:33
Did you push your fix already? I still noticed some green hue in this light

**Comment by wlbragg** [comment] 2018-07-31 01:49
@gilbertohasnofb yes, I pushed it. I think I may have noticed some color in the lower lighting conditions. In my case I think I see more yellow.
But, did this at least reduce the green considerably for you?
Can you post a new image to compare with your old image?

**Comment by gilbertohasnofb** [comment] 2018-07-31 12:25
@wlbragg I just tested it again and it reduced the green hue considerably, my light was yellow during all times of the day on my last test. @legoboyvdlp and @onox could you please test again and see if it solved for you as well?

**Comment by legoboyvdlp** [comment] 2018-07-31 14:00
Which branch - same as all the other 3D?

**Comment by gilbertohasnofb** [comment] 2018-07-31 14:01
Yes.

**Closed** 2018-08-07 22:12 UTC
Labels: bug, effects
