### ISSUE TITLE
Improvements to the top of the vertical stabilizer

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1030] opened 2018-03-28 15:43 UTC
Hi there,
A few more problems:
![image](https://user-images.githubusercontent.com/10434911/38039940-4e18cafc-32a6-11e8-9b63-175b623f4765.png)

Here we see that there are some strange lines on the top of the vertical stabalizer, with the N35799 livery.

OH-CTL was the other livery which I tested, which also presents the error:
![image](https://user-images.githubusercontent.com/10434911/38040225-eab193e4-32a6-11e8-9b0c-a5412393c4be.png)

Also, the model of the nav light is very unsmooth and not a great model:

This shows the top of the tail and light of a real Cessna:
![image](https://user-images.githubusercontent.com/10434911/38040041-88669752-32a6-11e8-84a4-2931c92fb433.png)

I circled a few things that in particular would be nice to have modelled:
![image](https://user-images.githubusercontent.com/10434911/38040274-0a642f4e-32a7-11e8-8a62-87e170b76e3d.png)

**Comment by wlbragg** [comment] 2018-03-28 16:09
Good catch on the tail light. I don't think it is even UV mapped at this point.

**Comment by wlbragg** [comment] 2018-03-28 18:27
There is tons of minor modeling upgrades (major ones too) that one could do on this aircraft. So if people want to identify these potential upgrades and make TODO issues for them go ahead. If someone else wants to do any of this remodeling, go for it.

All I did was to separate the current tail light and UV map it same as the other nav lights are. That is really all I am interested in doing.

@gilbertohasnofb we don't have to do this but to be consistent we probably should add a rudder nav light texture to the fuselage sheet. Below its the current mapping I did for the new rudder nav light object.
![nav](https://user-images.githubusercontent.com/11069680/38048576-62ad417a-328b-11e8-9801-db10d58d698b.jpg)

@legoboyvdlp that stripe coloring on top of the rudder is actually caused by the reflect shader, what your seeing is some part of the reflection cube we are using for c172p. There is nothing we can do about it as far as I am aware other than reshape the top of the rudder.

**Comment by gilbertohasnofb** [comment] 2018-03-28 19:41
@wlbragg sure, I will work on it right now.

**Comment by gilbertohasnofb** [comment] 2018-03-29 08:56
I just renamed this since now that light is textured but the suggested improvements to the 3D model have not been done. As @wlbragg I think we are both fine with the current state of the outside model (we need to find a point to stop and move on to other things) and now we plan to tackle the interior. But nevertheless we leave this opened sos that in the future these can still be considered.

**Comment by legoboyvdlp** [comment] 2018-03-29 12:41
I've been learning Blender. I'm not too confident, but perhaps after the interior work, I might be able to have a go. I will not promise that I can do it. But if I can, I will.

**Comment by gilbertohasnofb** [comment] 2018-07-29 20:47
@wlbragg I think if we did only two or three small improvements we could potentially close this issue as well:

* what if we simply added a cone object behind the light and let it 'enter' the rudder? I think this way we can easily model this part here: 
![image](https://user-images.githubusercontent.com/5700795/43370537-7a9e6ffe-9378-11e8-8844-8ea625d481c2.png)
* the other parts are much less relevant and we can simply skip them IMO. 
* I would like to fix this texture problem on the top part of the vertical stabilizer: 
![image](https://user-images.githubusercontent.com/5700795/43370559-f456fe4c-9378-11e8-8a13-e3398f408173.png)
* we could potentially make the vertical stabilizer and rudder a tiny bit thinner, ours look really thick comparable to the photos, but again this is a very small detail

**Comment by wkitty42** [comment] 2018-07-30 11:34
quick off-topic question about the photos above... the light on the top is the tail beacon and the one on the back is the white navigation light that goes with the red and green on the wings... what is the rectangular one on the side under the beacon? is there one on the other side in the same place? is this a tail strobe that would go with the wing strobes... i'm asking for my small AI GA craft lighting project...

**Comment by legoboyvdlp** [comment] 2018-07-30 12:35
That's an aerial for something - not sure what, but IIRC for VORs.

**Comment by wkitty42** [comment] 2018-07-30 14:20
erk! you're right... i see the stiff wire coming out of it now... i was hung up on some craft having more than two strobes on them... apparently some also have some additional ones on the tail area... thanks for the info :smile_cat:

**Comment by wlbragg** [comment] 2018-07-31 01:53
@gilbertohasnofb her is the first pass at retopologizing the tail section. I haven't touched the texturing. It will need to have the UV partially remapped. Please review and point out any issues when you get a chance.

![tail](https://user-images.githubusercontent.com/11069680/43432891-9b8314d2-943a-11e8-9edf-144aa60b596a.jpg)

**Comment by wlbragg** [comment] 2018-07-31 01:58
![tail2](https://user-images.githubusercontent.com/11069680/43433033-41c54cde-943b-11e8-8636-0b2a61e9b433.jpg)

**Comment by gilbertohasnofb** [comment] 2018-07-31 12:46
@wlbragg please do a `git pull` as I pushed some bug fixes to OH-CTL's tail texture and I also fixed the position of the IFR view as it was not changed after we lifted the cockpit.

**Comment by legoboyvdlp** [comment] 2018-07-31 13:57
Is it just me or is the top of the stabalizer slightly twisted after the circled part?

![image](https://user-images.githubusercontent.com/10434911/43464074-0841e4f8-94d2-11e8-921f-ddd7cd543fde.png)

**Comment by wlbragg** [comment] 2018-07-31 17:05
@legoboyvdlp there were two stages of work done on the stabilizer portion. I felt as it was pointing down after commit 
76d16dc so I adjusted it to be more level at the top line in commit 
00ac1d7 That also required moving the lamp mesh up ever so slightly. I didn't adjust the light however as it was so minuscule it wasn't worth it.
@gilbertohasnofb I fixed the gap in the beacon lamp.

**Comment by gilbertohasnofb** [comment] 2018-07-31 17:41
@wlbragg I found another issue, the VOR antennas are not touching the stabilizer:

![image](https://user-images.githubusercontent.com/5700795/43476759-4441236e-94f1-11e8-9e9c-17496ffcf319.png)

![image](https://user-images.githubusercontent.com/5700795/43476765-466e1520-94f1-11e8-872f-f5206f3ad4ec.png)

**Comment by wlbragg** [comment] 2018-08-01 03:54
Wow, I'm slipping, can't believe I missed that, thanks for catching it. It's pushed.

**Comment by gilbertohasnofb** [comment] 2018-08-01 09:34
Thanks, I confirm this is fixed.

**Comment by gilbertohasnofb** [comment] 2018-08-04 18:40
@wlbragg I've found a small bug, the strobe light isn't aligned any longer with the lamp. Also notice that there is a squareness to the light for some reason:

![image](https://user-images.githubusercontent.com/5700795/43679424-f142c562-981c-11e8-95d1-f0c600009392.png)
 
Also, (and please don't kill me and feel free to say no), I would like to suggest a couple of small improvements to the front part of the vertical stabilizer, if you think any of this would be possible. Using this reference:

![image](https://user-images.githubusercontent.com/5700795/43679482-bcc5d530-981d-11e8-95be-c21d72744d62.png)

We could:

* move the strobe light a bit backwards
* move VOR antennas a bit backwards
* strobe light should be shorter in height
* the base of the strobe light should be really short 
* the strobe lamp should be a dark unglowing red colour when off 
* the vertical stabilizer has a curved part in front of the strobe light

That is, going from this:

![image](https://user-images.githubusercontent.com/5700795/43679498-d7fb04ce-981d-11e8-9bd0-4614947e732e.png)

To this:

![image](https://user-images.githubusercontent.com/5700795/43679512-23914560-981e-11e8-81d3-8d129f0a436c.png)

(open them in two tabs and flick between them to see the differences)

Needless to say none of this is super high priority, so just let me know your thoughts.

**Comment by wkitty42** [comment] 2018-08-04 19:01
On 08/04/2018 02:40 PM, Gilberto Agostinho wrote:
>   * move the strobe light a bit backwards
>   * strobe light should be shorter in height
>   * the base of the strobe light should be really short
>   * the strobe lamp should be a dark unglowing red colour when off


do you mean the beacon? beacons are red whereas strobes are a brilliant blueish 
white when they flash... think of strobe lights in a disco or dance club... the 
ones that make everything look like stop-motion... like when fan blades are 
moving but they look like they are still...

there are a lot of folks that mix these up... they say strobe when they mean 
beacon... beacons are the red ones that used to revolve and shine their light as 
a beam but now generally just blink omni-directionally... they are located on 
the top of the tail or fuselage and possibly there may be one on the belly of 
the fuselage... strobes are generally on the wing tips with the navigation 
lights and maybe on the tail with the white tail navigation light...

**Comment by gilbertohasnofb** [comment] 2018-08-04 19:06
Yeah, nice catch, I meant the red beacon.

**Comment by gilbertohasnofb** [comment] 2018-08-04 19:25
> FYI: I am in the middle of light map correction, it's a bitch. We did so much customization prior, it is all I can do now. I can't simply re-run whole maps for the interior, panel and panel-parts. Lots of cutting and paste. But it'll work. The next person that come along to work on this will hate us!

Oh please don't worry about that! Just make sure to generate the new light maps containing the new objects and let me do the copy pasting, I have all modified files in my folder. And actually the light map is the least of my concern as most objects are small and simple and I could just fake it with GIMP. Please dont' go too crazy with it, ok?

**Comment by wlbragg** [comment] 2018-08-04 19:45
Actually it's the baking that is the time killer for me. I find it almost impossible to get consistent bakes, especially over time, with Blender. There are too may settings and variables. One way for AO and another for light maps. Add into that all the customization I had to do in the blend to get a map that has shadows for some things but not for others, whew.

I'll tell you what then. I already did lm-panel.png as it is a very special and customized map, done in many stages. I'll push what I did and also include lm-panelORG.png which is the original before my changes so you can look at it and verify all is well.

Then I will gladly post the new bakes lm-panel-parts and lm-interior for you to do the cut and paste from. I should have them in an hour or so.

Then I will do the same for the AO and post it for you to combine the new parts into your master.

**Comment by gilbertohasnofb** [comment] 2018-08-04 19:48
@wlbragg perhaps do not push the new bakes but just post them here, so that I can just take a look at them before we commit them, would that be all right? 

> Apologies for cluttering this thread with "off topic" stuff.

No worries, we don't have an opened issue for that and we are multitasking a million issues at the same time, it's all good.

**Comment by wkitty42** [comment] 2018-08-04 22:44
On 08/04/2018 03:06 PM, Gilberto Agostinho wrote:
> Yeah, nice catch, I meant the red beacon.


not a problem... i was real hopeful that it wouldn't come across offensively...

**Comment by wlbragg** [comment] 2018-08-05 09:08
Done!

**Closed** 2018-08-07 22:12 UTC
Labels: 3D model, bug, enhancement, textures
