### ISSUE TITLE
Copilot's legs pierce copilot's pedals

### ISSUE THREAD

**Issue by TeXnicer** [c172p-team/c172p#464] opened 2015-10-09 09:14 UTC
![copilot_feet](https://cloud.githubusercontent.com/assets/15046612/10390132/f3579788-6e76-11e5-9bbc-68cecb49fdcf.png)

**Comment by gilbertohasnofb** [comment] 2015-10-09 09:19
This is a known issue, but I don't think we had specifically created a GitHub Issue about this. We have some other opened issues about the human models though:

https://github.com/Juanvvc/c172p-detailed/issues/417
https://github.com/Juanvvc/c172p-detailed/issues/429
https://github.com/Juanvvc/c172p-detailed/issues/423

And as a side note, I believe the pilot's feet also collide with the rudder, so when fixing this we have to do it for both co-pilot and pilot.

**Comment by TeXnicer** [comment] 2015-10-09 09:21
Ack thanks for review of my issue reports. I keep going on since I use the 172P for my Germany tour. Besides thank you for such an amazing piece of work. Won't do the 500s-leg tour if the model was not wonderful. So regard my reports as minor probs only ;)

**Comment by gilbertohasnofb** [comment] 2015-10-09 09:23
@TeXnicer Thanks for the kind words. We appreciate these reports very much, as it helps us improve the plane, so feel free to create more issues if you see anything strange.

**Comment by onox** [comment] 2018-08-10 21:03
Duplicate of of #417

**Closed by onox** 2018-08-10 21:03 UTC
Labels: 3D model, bug
