### ISSUE TITLE
Add non-ALS lightmaps

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1192] opened 2018-08-28 12:20 UTC
Add non-ALS lightmaps for non-ALS users doing night flights.

The current lightmaps require ALS. The aircraft cannot do night flights presently without ALS. User "Megaf" has been complaining about this on Discord.

It is possible to add non-ALS lightmaps which require only the Model shader using model-combined-deferred as seen on the IDG-A32X - would it be possible to add these, enabled only when ALS is off?

**Comment by dany93** [comment] 2018-08-28 12:50
Understanding where the issue is seems even more complicated.
[I do not have the instrument lightings](https://github.com/c172p-team/c172p/issues/438#issuecomment-405266678) (post lights) even with ALS "ON" (although ALS works by elsewhere).
They should be activated by the "Radio lighting" knob.

**Comment by gilbertohasnofb** [comment] 2018-08-28 13:47
> Add non-ALS lightmaps for non-ALS users doing night flights.

@wlbragg and I had a conversation about this once, it is quite difficult to cater for three different rendering systems and for users using different shader levels. Personally, I think FG is a mess with these three rendering systems (and two weather modes).

**Comment by wlbragg** [comment] 2018-08-28 15:43
@legoboyvdlp one thing you might suggest to "Megaf" is what he is seeing is totally realistic. The two lights he does get are the only ones that aircraft have on some models, that is why he has a red flashlight. Dos it work? It still doesn't give him the red flood and white dome lights which he should always have, all models.
Why wouldn't the "alternate non-ALS" light maps use the same maps we already made. In other words, why would we have to create new map. We couldn't just make the new non-ALS effect using the existing maps?

**Comment by gilbertohasnofb** [comment] 2018-08-28 15:52
@wlbragg I think you might have misunderstood what lego wrote, but it seems to me that the user he mentioned does not use ALS, he is probably on either Rembrandt or default rendering. This means that he does get those two instruments with the RADIO LT (which is realistic) but he likely does not get the post and flood lights since those depend on ALS, right? Therefore he is complaining that without ALS he is not able to do proper night flights.

**Comment by legoboyvdlp** [comment] 2018-08-28 16:37
Gilberto is correct.

**Comment by wlbragg** [comment] 2018-08-28 17:03
I wasn't clear in what I said. Two points I was making.
If he is not using ALS then he has a realistic c182p without post lighting. This is how they are without post lighting and he can do a night flight, we have a video of a pilot dong a night flight without post light and only the two integral lit instruments. He can use the flashlight maybe in place of the red flood that that pilot appeared to use. I was pointing out that all the 172p's should have that red flood and that is something he should have but doesn't because it is ALS, so use the red flashlight as a substitute.

As far as the light maps. I was wondering why we can't adapt the same light map images, the .png's, to use in the non-ALS shader framework @legoboyvdlp mentioned. Wouldn't that use the same light map images or are they different? Isn't it just a matter of making a different effect file pointing to model-combined-deferred?
>It is possible to add non-ALS lightmaps which require only the Model shader using model-combined-deferred as seen on the IDG-A32X

**Comment by HHS81** [comment] 2018-08-31 14:59
I'm a bit confused. You should always use model-combined-
deferred. But so much as I remember Default only allows one lightmap channel,  while the ALS allows 4 channels,  and with some magic 12. Wlbragg known how the latter works.

And that is why I agree to Gilberto - 3 rendering to support, 2 of them too much. I just have mentioned the issue yesterday to the devel-list. Don' t need to tell how Thorsten Renk answer was ...

**Comment by onox** [comment] 2018-08-31 17:51
IMO we can close this as a won't fix.

**Comment by legoboyvdlp** [comment] 2018-08-31 18:59
Fair enough. Thanks.

**Comment by Megaf** [comment] 2018-08-31 21:04
Just to be clear, I was expecting **at least** something like this without ALS. This is @HHS81 c182S.
![image](https://user-images.githubusercontent.com/6201512/44935668-98b57400-ad69-11e8-8e5e-4e6b02cd9d35.png)

However, we can have some nice visual effects without ALS, as in the 707.
"Domelight" off, instruments brightness max
![image](https://user-images.githubusercontent.com/6201512/44935707-c7334f00-ad69-11e8-9e47-af3d3b0a1ed6.png)

"Domelight" max.
![image](https://user-images.githubusercontent.com/6201512/44935723-cf8b8a00-ad69-11e8-8902-f70acb5a58b2.png)

**Comment by Megaf** [comment] 2018-08-31 21:43
I think it'd be interesting to compare with the F-14.
No ALS nor Rembrandt, all shaders set to minimum or disabled. And we have an effect of red flood light.
![image](https://user-images.githubusercontent.com/6201512/44937044-44ad8e00-ad6f-11e8-894d-222a1d0d2af8.png)

So my point is, ALS is not required. And shouldn't be.

**Comment by wlbragg** [comment] 2018-08-31 21:59
I think you might miss the point that the shot with only two lit instruments is accurate to a c172p with no post lighting. The integral lighting was never realistic. There is a video showing a pilot flying at night with only those two instruments and a red flood, (which admittedly you don't even have the red flood). Does the flashlight work for you?

**Comment by wlbragg** [comment] 2018-08-31 22:00
It's not an issue of not knowing how to give you the lighting you want. The issue is in the authenticity.

**Comment by Megaf** [comment] 2018-08-31 22:04
![image](https://user-images.githubusercontent.com/6201512/44937657-3dd44a80-ad72-11e8-8ee2-1a51914b1f4d.png)

**Comment by Megaf** [comment] 2018-08-31 22:05
And I would be very happy with a simulated red flood light only.

**Comment by HHS81** [comment] 2018-08-31 22:15
@wlbragg 
The problem of Megaf is, that he he don't have any lighting because he doesn't use ALS as render. Just the Default renderer. 
So at least there should be a fallback. And I think by using the material animation, it should be perfectly possible to have the flood and post light.

**Comment by legoboyvdlp** [comment] 2018-08-31 23:37
It ia impossible to add the post light uaing a material animation, but a basic red flood light is certainly possible.

**Comment by legoboyvdlp** [comment] 2018-08-31 23:39
@Megaf just out  of interest, I take it the lightmaps do not work at all even with the model shader set to full and no ALS?

**Comment by Megaf** [comment] 2018-08-31 23:51
That is correct, everything is simply black without ALS.
![image](https://user-images.githubusercontent.com/6201512/44939936-1638ae80-ad81-11e8-9bf7-42ef17f9ffa4.png)

**Comment by HHS81** [comment] 2018-09-01 00:39
Tzhe post light illuminates the instruments, right? 
That's all what he want to see.....

**Comment by Megaf** [comment] 2018-09-01 01:28
By the way, I've spent the last hour watching c172 night flights, most of them have instruments lights.
https://www.youtube.com/watch?v=OAKV_NYN75I

**Comment by wlbragg** [comment] 2018-09-01 04:47
>The post light illuminates the instruments, right?
That's all what he want to see.....

Right, that is what the light maps reproduce. We have had considerable discussion about this and it was decided that we wouldn't support a full integral lighting system (material animation), because they don't come that way in real life. If they don't have post lighting then they only have the oil and rpm (and maybe the egt) with integral lighting. That is what we did. We decided you actually can fly at night with this configuration as there was a video to support this. It was also suggested early on, by me, as a fall back for older hardware to include the full set of integral lighting with the lower shader settings. That is what the FG version of the c172p had originally. But we again decided against the idea to continue to support the older technology. I guess we kind of drew a line in the sand.

>That is correct, everything is simply black without ALS.

Then you have a problem as you should still have the oil temp and pressure and the RPM lit up as integral lighting controlled by the radio dial. I do understand now that the flashlight only works with ALS so you can't use that as a replacement for the white dome or red flood lighting.

>By the way, I've spent the last hour watching c172 night flights, most of them have instruments lights.

Again, that is post lighting which is what the light maps represent.

>So at least there should be a fallback. And I think by using the material animation, it should be perfectly possible to have the flood and post light.

Yes, and if I was to to that I would have the material animation lights only available if ALS was off. I offered to do this and it was decided not to accommodate. I suppose if enough people request it maybe we would change our minds.

None of us make these decisions on our own. It is always a consensus.

I really don't think we should change our decision for one user. If it is an issue for many, then that might make a difference. We can't support older technology indefinitely. We would still be line graphics if that were the case.

@Megaf I can give you a suggestion that i don't like as an overall solution for everyone with this issue. But if you open each instrument's .xml in
/Models/Interior/Panel/Instruments/*the instrument*
you will see the following in every one of them...
~~~
<!--animation>
        <type>material</type>
        <object-name>Face</object-name>
        <object-name>PtrTip</object-name>
        <emission>
            <red>  1.0</red>
            <green>0.8</green>
            <blue> 0.5</blue>
            <factor-prop>/sim/model/material/instruments/integral-factor</factor-prop>
        </emission>
    </animation-->
~~~
Remove the comment tags so they look like this
~~~
<animation>
        <type>material</type>
        <object-name>Face</object-name>
        <object-name>PtrTip</object-name>
        <emission>
            <red>  1.0</red>
            <green>0.8</green>
            <blue> 0.5</blue>
            <factor-prop>/sim/model/material/instruments/integral-factor</factor-prop>
        </emission>
    </animation>
~~~
and you will have your integral lighting. That is the best I can do right now.

**Comment by Megaf** [comment] 2018-09-01 17:04
Sorry, I think I was not clear on my previous comment here, everything is black BUT rpm and oil.
I will simply not fly the c172p anymore. Without ALS or anything really it's already too heavy and too taxing on my hardware.

Besides, the FDM is getting worse with each release, that left roll is absolutely unreal. It's too strong and it stays the same way no matter the stage of the flight, engine power or speed.

Also, it stalls all the time! c172p is a forgiving airplane in real life, it should stall so easily.

I will just be flying the c182s instead. It feels rights, I can see the instruments at night and it has all complex and realistic procedures I was looking for.

I suggest you use that airplane as reference.

**Closed** 2018-09-02 15:48 UTC

**Comment by Megaf** [comment] 2018-09-02 16:27
Thank you @legoboyvdlp and @onox

**Comment by wlbragg** [comment] 2018-09-03 20:17
>I'm a bit confused. You should always use model-combined-
deferred. But so much as I remember Default only allows one lightmap channel, while the ALS allows 4 channels, and with some magic 12.

I noticed this statement and while working on something else looked into this.
We are using model-default for the ALS interior stuff, not model-combined-
deferred which I think is part of the exterior model-combined scheme.

**Comment by HHS81** [comment] 2018-09-03 20:35
@wlbragg 
Yeah, I might be wrong as it is quite confusing. 
As an example I wanted to implement ALS-interior shadows for the EC 135 P2, but their lightmap didn't work with default/ rembrandt.

**Comment by wlbragg** [comment] 2018-09-04 02:43
@HHS81 

>>But so much as I remember Default only allows one lightmap channel, 
>model-combined-
deferred which I think is part of the exterior model-combined scheme.

I was also surprised to learn that model-combined-
deferred can also use the multi-channel light maps and even under Rembrandt, or so my test indicated. But you still can't use both strategies at the same time on the same model mesh.
